### ISSUE TITLE
[T2 - P1.a] Duda con lo que se pide hacer

### ISSUE THREAD

**Issue by pedroriosg** [IIC2343/Syllabus-2023-1#100]
Hola! Estoy revisando la tarea y no entiendo muy bien que se pide hacer en la pregunta a.

Muchas gracias

**Comment by Geeermy** [comment]
Hola Pedro, ten cuidado con la forma en la que preguntas porque atenta contra la integridad académica dar posibles respuestas aquí. A la próxima escribe un correo a los/as ayudantes o a mí si necesitas entregar más información de la necesaria para ser respondido.

Respecto a tu duda en sí: Necesitan modificar el _hardware_ para poder considerar todas las instrucciones pedidas, pero no necesariamente todas estas requieren de dichas modificaciones, en esos casos pueden indicar cómo a partir de las señales de control. No hay problema con eso.

Saludos.

**Comment by pedroriosg** [comment]
Perdón! Como esa información era necesaria para el proyecto la asumí como "pública".

Muchas gracias de todas maneras!
