### ISSUE TITLE
[T2 - P1.a] Duda con A,(A)

### ISSUE THREAD

**Issue by piacabrera** [IIC2343/Syllabus-2023-1#101]
Hola! mi duda viene ya que en una issue anterior se pregunta que hace B,(A) y dicen que guarda B operación Mem(A) en B, pero en el caso de A, (A), seria guardar B operación Mem(A) en A?, ó A operación Mem(A) en A? 

Muchas gracias de antemano.

**Comment by Geeermy** [comment]
¡Hola Pía!

Acá se espera que implementen el segundo caso, es decir, $A = A op Mem[A]$

¡Saludos!

**Comment by Francisco-Morales-R** [comment]
@Geeermy
Aquí, solo para aclarar entonces:
Cuando se tiene OP1 A, (A) debemos guardar 'A op1 Mem[A]' en A
y cuando tenemos OP1 B, (A) debemos guardar 'B op1 Mem[A]' en B?
Que el enunciado me lo deja medio confuso

**Comment by Geeermy** [comment]
@Francisco-Morales-R sip, lo que señalas es lo esperado. :)

¡Saludos!

**Comment by Francisco-Morales-R** [comment]
@Geeermy Oka, Muchas Gracias!

**Comment by stgo32** [comment]
Otra duda, Mem(A) se refiere a una direccion de memoria cualquiera o a la que se encuentra en el registro A? Lo digo porque A op Mem(A) parece redundante

**Comment by Geeermy** [comment]
@stgo32  Se refiere al elemento almacenado en la dirección indicada por $A$. No es redundante. Por ejemplo, podríamos tener $A = 3$ y el valor de memoria $Mem[3] = 7$. De esta forma, por ejemplo, si tenemos $ADD A,(A)$, lo que haríamos sería $A = A + Mem[A] = 3 + 7 = 10$. Son valores distintos.

¡Saludos!

**Comment by stgo32** [comment]
Perfecto gracias
