### ISSUE TITLE
[T2 - P3] Duda Assembly

### ISSUE THREAD

**Issue by mpenalozag** [IIC2343/Syllabus-2023-1#102]
Hola! En el enunciado, en la pregunta 3, dice que tenemos que ordenar arreglos de enteros. Al tratar de usar números negativos el simulador de linux no guarda los valores correctamente. ¿Que se hace al respecto?

Gracias de antemano!

**Comment by Geeermy** [comment]
¡Hola!

Veré qué sucede, pero por mientras asume que está bien tu algoritmo si funciona con números positivos (incluyendo el cero).

¡Saludos!

**Comment by frvalenzuela** [comment]
Hola @mpenalozag !

Estuve tratando de usar un programa simple como:

```
DATA:
var1 -7
var2 -2
CODE:
MOV A,(var1)
MOV B,(var2)
ADD (var1)
```

Y tuve este resultado:

<img width="630" alt="image" src="https://user-images.githubusercontent.com/20147482/234134664-cebbe2a8-1151-46eb-a5ec-ecd3fa021c7b.png">

Como puedes ver pude tratar con números negativos sin mayor complicación. 

Quedo atento a tu respuesta.

¡Saludos!

**Comment by mpenalozag** [comment]
Ahi probé y efectivamente funciona. El problema es con números menores a -128. 

Muchas gracias!

**Comment by Geeermy** [comment]
@mpenalozag eso tiene que ver por el uso del complemento a 2 jeje. A modo de prueba podrías probar con números mayores a 127 también, deberían tirar _overflow_. :)
