### ISSUE TITLE
[T2 P2.b] Duda cantidad de instrucciones a incluir

### ISSUE THREAD

**Issue by berrazuriz3** [IIC2343/Syllabus-2023-1#103]
Hola, una duda, cuales son las instrucciones que tenemos que incluir? No me queda claro porque en el enunciado solo dicen set de instrucciones

**Comment by Geeermy** [comment]
Primero, gracias por hacer la _issue_ separada. 😄 

Respecto a tu pregunta: Tú defines las instrucciones de la máquina según lo pedido (por ejemplo, tú debes escoger un nombre para la instrucción que sume los dos valores al tope del _stack_). Ahora, en cuanto operaciones, se espera que para esta pregunta incluyan:

- Todas las operaciones aritméticas y lógicas de 2 operandos: `ADD`, `SUB`, `AND`, `OR`, `XOR` (que inciden en los dos valores al tope del _stack_).
- Todas las operaciones aritméticas y lógicas de 1 operando: `NOT`, `SHL`, `SHR`.
- Operación de ingreso de un literal al tope del _stack_.
- Operación de descarte del tope del _stack_.

No deben incluir instrucciones de direccionamiento, solo las señaladas anteriormente.

Luego, en la 2.c. deben incluir instrucciones para salto (`JMP`, `JEQ`, etc.) y en la 2.d para subrutinas (`CALL` y `RET`).

¡Saludos! 😃

**Comment by fedezang** [comment]
Sobre las instrucciones, para la resta por ejemplo, puedo el orden de operación que estime conveniente? Es decir, puedo hacer: 2do elemento de stack - 1er elemento de stack? o debo incluir ambas posibilidades?

**Comment by Geeermy** [comment]
@fedezang Sí! Ningún problema. :)

**Comment by fedezang** [comment]
Gracias!

**Comment by Geeermy** [comment]
@Jpuc1143 No es estrictamente necesario que la incluyas, pero puedes hacerlo si deseas. :) El ADD mínimo que se espera es el que sume los dos valores del tope del _stack_.

¡Saludos!

**Comment by Francisco-Morales-R** [comment]
@Geeermy Holaa,
En este caso dijiste que no era necesario incluir instrucciones de direccionamiento. Eso aplica para los incisos b, c y d también?
