### ISSUE TITLE
[T2 P1.a] Mux

### ISSUE THREAD

**Issue by JoseTomasSoto** [IIC2343/Syllabus-2023-1#105]
Puedo modificar los MUX, ej: hacer que reciban mas inputs, y tengan más señales?

**Comment by Geeermy** [comment]
¡Hola!

Sí, ningún problema. :)

¡Saludos!

**Comment by JoseTomasSoto** [comment]
buenisimo. Y puedo al usar el Literal que entra al MuxB, puedo decidir el valor que tendra? Gracias!

**Comment by Geeermy** [comment]
Depende de la instrucción que quieras ejecutar, pero siempre que lo explicites en el desarrollo para que siempre se haga de esa manera para dicha instrucción está OK (esto sería responsabilidad del Assembler). 🤓
