### ISSUE TITLE
[T2 - P3] Algoritmo de Sorting

### ISSUE THREAD

**Issue by fedezang** [IIC2343/Syllabus-2023-1#106]
Hola! Para esta pregunta, solo se puede implementar el algoritmo que se describe (min-max sort)? o puedo ocupar algún otro algoritmo que ordene el arreglo?

**Comment by Geeermy** [comment]
¡Hola!

Debe ser min-max sort.

¡Saludos!

**Comment by Geeermy** [comment]
¡Hola Nano!

Sí, no hay problema con que exista más de un _swap_ siempre que el algoritmo funcione como min-max sort, esto es: asegurar que al final de cada iteración los extremos de cada sub-arreglo posean el mínimo y máximo ubicados correctamente.

¡Saludos!
