### ISSUE TITLE
[T2] Link draw.io

### ISSUE THREAD

**Issue by illanes00** [IIC2343/Syllabus-2023-1#107]
Hola! Espero que estén bien.

Les quería consultar sobre el link de los archivos draw.io (https://drive.google.com/file/d/1dAfG4klcrDHpncHELQRHue4Q3PrqxVSy/view?usp=sharing) el cual actualmente me aparece caído.

Existe alguna copia de esos archivos u otro link que se pueda usar?

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

Disculpa, fue mi culpa. Limpié los archivos de la cuenta y se me olvidó que había dejado el diagrama en ella. Acabo de subirlo de nuevo y lo puedes encontrar aquí: https://drive.google.com/file/d/1ZWtySPI5nQ9lm3Iq2MwsQ5bcdbYenog7/view?usp=sharing

Actualizaré el enunciado para que aparezca de nuevo también. Gracias por el aviso. :)

¡Un abrazo!

**Comment by illanes00** [comment]
Muchas Gracias!!

**Comment by Geeermy** [comment]
Solo por si acaso: agregué a la pestaña de la máquina de _stack_ el registro auxiliar, no lo había incluido en el diagrama original pero debía estar.

Ahora sí: ¡buenas noches! :)
