### ISSUE TITLE
[T2 - P3] Division entera (SHR)

### ISSUE THREAD

**Issue by diegocostares** [IIC2343/Syllabus-2023-1#108]
Hola, quisiera saber cuál es la sintaxis para hacer una división entera en Assembly, es decir: `5 // 2 = 2` 

Probé con muchas variaciones de SHR para un A=5 y nunca se modificó mi valor de A

**Comment by Geeermy** [comment]
¡Hola!

La nomenclatura debería ser `SHR A,A`. ¿Puedes probar con eso? Si no, lo reviso en detalle y te cuento.

¡Saludos!

**Comment by Geeermy** [comment]
Disculpa, pero acabo de revisar el material y no es así. Mira:

<img width="655" alt="Captura de Pantalla 2023-04-25 a la(s) 13 57 01" src="https://user-images.githubusercontent.com/5559611/234362266-e7f87ab6-5951-4154-980f-fe4dfa2c41f2.png">

Esta imagen es un extracto directo de las clases (diapositiva 27).

Creo que lo que pasó fue que te confundiste con `SHR (dir)`:

<img width="424" alt="Captura de Pantalla 2023-04-25 a la(s) 13 57 16" src="https://user-images.githubusercontent.com/5559611/234362505-94ccc527-cb99-4705-8302-100dfc6fa962.png">

Donde lo que hacemos es guardar en la dirección `dir` el _shift right_ de $A$ (diapositiva 33).

Puede no parecer intuitivo pero se lee de la forma: "guardar en el registro $A$ el resultado de la operación `SHL A`".

Si hubiera una diapositiva donde la instrucción se usara como indicas en tu comentario por favor señálamelo, porque yo no la encontré. De todas formas, te invito a revisar el listado de instrucciones completo del computador básico en la Clase 7 (Arquitectura de Computadores) de la sección 2, ahí está todo más compacto.

¡Saludos!

**Comment by diegocostares** [comment]
Sale en la diapositiva 43 del ppt de la clase 5 de la sección 2

**Comment by Geeermy** [comment]
Sigue estando bien. En ese ejemplo, `SHR (a)` no alude al registro `A`, sino que a la variable `a` (puedes ver que está definida en el segmento `DATA`). Eso se condice con la instrucción `SHR (Dir)`, no `SHR A,A`. De todas formas tomaré en cuenta la confusión para cambiar los valores de esas variables y evitar malos entendidos.

¡Saludos!
