### ISSUE TITLE
[T2 - P1.b] Bibliografía de instrucción 

### ISSUE THREAD

**Issue by Jpuc1143** [IIC2343/Syllabus-2023-1#109]
Hola, mientras estaba pensando que instrucción implementar me acorde de una página de Wikipedia que explicaba una particular instrucción que estaba en algunas ISAs. ¿Es valido tomar está instrucción como inspiración si es que cito la página correctamente?

**Comment by Geeermy** [comment]
¡Hola!

Sí, no hay problema. Cítalo y explica bien qué hace dicha instrucción y la adaptación que hiciste en la microarquitectura para implementarla. Recuerda que no es válido si ya se puede ejecutar sin modificar la arquitectura.

¡Saludos!
