### ISSUE TITLE
[T2 - P1.bcd] Responder tres incisos al mismo tiempo

### ISSUE THREAD

**Issue by Jpuc1143** [IIC2343/Syllabus-2023-1#110]
Hola, es posible hacer solo un diagrama y set de instrucciones para responder los incisos b, c y d de la pregunta 2? No veo que ninguno de los incisos requieran quitar algún elemento del inciso anterior así que sería redundante tener 3 diagramas con diferencias minimas.

**Comment by Geeermy** [comment]
¡Hola!

Lamentablemente no. La idea es ver cómo va evolucionando la complejidad de tu arquitectura con las modificaciones adicionales que tiene cada inciso. Lo que sí, puedes incluir en las partes c y d solo las instrucciones nuevas que se añaden, no es necesario que incluyas la tabla completa siempre. Sí es importante poner los diagramas para ver qué adiciones hiciste sobre el diagrama en b para implementar saltos y lo mismo para d para implementar subrutinas.

¡Saludos!
