### ISSUE TITLE
[T2 - Templates diagramas]

### ISSUE THREAD

**Issue by IgnAMS** [IIC2343/Syllabus-2023-1#111]
Hola! Estoy intentando abrir los templates pero me tira el siguiente error: 
![imagen](https://user-images.githubusercontent.com/42097387/234311908-aacf55db-f202-4b6c-902d-abf53a2f9b48.png)

Podrían subirlo al github a lo mejor?

**Comment by IgnAMS** [comment]
Gracias profesor! Ahí me funcionó. También me fijé que el enunciado dice que son 3 templates, pero no entendí bien como abrirlos, en draw.io me sale solo lo siguiente:
![imagen](https://user-images.githubusercontent.com/42097387/234416517-39b068fb-cc51-4899-9575-f4f0a423fc82.png)

Saludos!

**Comment by Geeermy** [comment]
Justo en donde cortas el pantallazo (parte inferior) se ven tres pestañas. Cada pestaña tiene un diagrama distinto (algo así como las hojas en excel). Avísame si las logras ver.

¡Saludos!

**Comment by IgnAMS** [comment]
Lol sí. Muchas gracias :D
