### ISSUE TITLE
[T2 - P3] Assembly

### ISSUE THREAD

**Issue by isantanderm** [IIC2343/Syllabus-2023-1#112]
Hola ¿Dónde puedo encontrar información o algún texto sobre cómo escribir un _Assembly_ correctamente?

**Comment by Geeermy** [comment]
@maxcorvalan Por favor referirse a #97. En resumen: debes entregar sí o sí un `.txt` con tu código y, si quieres, complementar con un `.pdf` donde expliques lo que hiciste.

¡Saludos!
