### ISSUE TITLE
[T2 - P2.b] Eliminar último dato del stack

### ISSUE THREAD

**Issue by a-ck** [IIC2343/Syllabus-2023-1#115]
Hola, eliminar el último dato puede ser dejarlo en 0? o cómo se elimina?

**Comment by a-ck** [comment]
O acaso es dejar el SP un valor más abajo no más?

**Comment by Geeermy** [comment]
¡Hola Antonia!

Sería lo segundo. Cambiarlo el dato a 0 sería sobreescribirlo, no descartarlo. Al cambiar el _stack pointer_ ($SP$) decimos que efectivamente lo descartamos, ya que se asume que ya no es parte de la memoria de _stack_ (puedes ver cómo funcionan las instrucciones `POP A`, `POP B` como referencia).

¡Saludos! :)

**Comment by a-ck** [comment]
Perfecto, gracias
