### ISSUE TITLE
[T2 - P1.b] Modificar hardware 

### ISSUE THREAD

**Issue by catalinacarter** [IIC2343/Syllabus-2023-1#117]
Hola! Tengo una duda sobre qué se considera válido como modificar el hardware. Si no agrego ningún componente, pero agrego **SOLO señales para realizar una cierta instrucción**, cuenta como modificación? Estas señales serían nuevas, no existen en el computador básico. 
Muchas gracias :)

**Comment by Geeermy** [comment]
¡Hola Cata!

Si es solo incluir señales de control no existentes en componentes que las podrían tener pero en la arquitectura no se usan (como por ejemplo `L`, `Inc` o `Dec`), entonces no, ya que es una modificación trivial. Debiese existir al menos un nuevo componente **o** conexión entre componentes que no hubiera existido antes (también se puede complementar con las señales que quisieras agregar, si es que te sirvieran).

¡Saludos!
