### ISSUE TITLE
[T2 - P1.b] Duda instrucción nueva

### ISSUE THREAD

**Issue by AlonsoZamorano** [IIC2343/Syllabus-2023-1#118]
Una consulta rápida, cuando dice **una instrucción nueva** significa que elegimos una instrucción que se nos ocurra (que no hayamos visto), que expliquemos que hace y crear el hardware para hacerla en una iteración no?

**Comment by Dafnemami** [comment]
Vi en otra issue q no es necesario q sea en una iteración

**Comment by Geeermy** [comment]
Respondiendo a ambos:

1. Claro, justamente eso. Ahora, como alternativa también pueden crear conexiones nuevas entre componentes ya existentes para sus instrucciones.
2. Como dice @Dafnemami, puede tomar más de un ciclo tu instrucción, pero la idea es que se ejecute haciendo uso de tus modificaciones.

¡Saludos!
