### ISSUE TITLE
[T2 - P2.c] Instrucción CMP

### ISSUE THREAD

**Issue by fedezang** [IIC2343/Syllabus-2023-1#119]
Hola! En el caso de la máquina de stack, ¿Cómo sería esta instrucción? ¿Compara los primeros 2 elementos del stack?¿O compara el último elemento del stack con el registro auxiliar?

**Comment by Geeermy** [comment]
¡Hola!

Depende de cómo lo quieras implementar, pero por consistencia se esperaría que sea con los 2 elementos del _stack_ (puedes seguir el mismo orden en el que haces las operaciones).

¡Saludos!
