### ISSUE TITLE
[T2 - P3] Duda sobre el output

### ISSUE THREAD

**Issue by pedroriosg** [IIC2343/Syllabus-2023-1#120]
Hola, como debe ser el output a final del algoritmo? Se tiene que ver el arreglo ordenado en la RAM nomás? Si es así, se pueden implementar un arreglo auxiliar en donde vaya guardando mis datos ordenados? O se debe ir actualizando el arreglo original?

Saludos y gracias

**Comment by Geeermy** [comment]
¡Hola!

Ambas opciones son válidas, aunque el ideal sería mantener el mismo arreglo.

¡Saludos!
