### ISSUE TITLE
[T2 - P3] Duda sobre assembly

### ISSUE THREAD

**Issue by pedroriosg** [IIC2343/Syllabus-2023-1#121]
Hola! cómo puedo traer el valor que está en la posición X en la memoria,  cuando X es una variable?

Me pasa que si defino esto

```
DATA:
   posicion_a_traer 5

CODE:
  MOV A, (posicion a traer)
```

Trae al registro A un 5 y no el valor en la posicion 5. No se si se entiende

**Comment by Geeermy** [comment]
¡Hola!

Puedes usar direccionamiento indirecto:

```
MOV A,(posicion_a_traer) ; A = 5
MOV B,arr                ; B = dirección de memoria arr.
ADD B,A                  ; B = dir. arr + 5 = sexto elemento del arreglo
MOV A,(B)                ; A = arr[5]
```

¡Espero que se entienda!
