### ISSUE TITLE
[T2 - P2.b] Opcodes

### ISSUE THREAD

**Issue by rosariodominguezm** [IIC2343/Syllabus-2023-1#122]
Hola! Entiendo que para la máquina de stack van a haber operaciones que usen más de un ciclo. No me queda muy claro del enunciado donde dice "recuerde que un opcode se asocia a un ciclo de ejecución, por lo que puede tener instrucciones asociadas a más de uno". 

¿Esto es que si una instrucción tiene 3 ciclos, por ejemplo, anoto 3 opcodes diferentes que representen a esa instrucción? Como que no me hace tanto sentido usar opcodes si es que no me simplifica la representación de las señales. ¿Podría usar solamente la combinación de señales como opcode?

Gracias!

**Comment by Geeermy** [comment]
¡Hola Rosario!

Cada _opcode_ representa una operación que se realiza en un ciclo. Por ejemplo, veamos en el computador básico las instrucciones `RET` y `POP`:

<img width="925" alt="Captura de Pantalla 2023-04-26 a la(s) 17 49 33" src="https://user-images.githubusercontent.com/5559611/234710629-cb9d5399-252c-4083-88b1-b1634cd9cf8a.png">

Vemos que ambas tienes dos _opcodes_, pero que coinciden en el primero: `01111111`. Esto es porque ambos requieren de la misma operación inicial: La que activa la señal `IncSp` para posicionar el _stack pointer_ en la dirección del último elemento ingresado en el _stack_. Entonces, si una instrucción requiere 3 ciclos (con operaciones distintas cada uno), entonces sí habría que asociar tres _opcodes_ que representen las 3 operaciones que realizarás. La gracia es que dichos _opcodes_ pueden reutilizarse en otras instrucciones (como pasa en `POP` y `RET`).

Ahora, el por qué usar _opcodes_ en vez de la concatenación de las señales de control lo vimos en clases: A pesar de que es más directo hacer esto, tenemos dos problemas:

1. Si agrego más señales de control, usaré palabras de memoria más grandes en mi memoria de instrucciones. No siempre podemos hacer esto.
2. No vamos a ocupar todas las combinaciones de señales de control posibles. Por ejemplo, en la ISA del computador básico no existe instrucción alguna donde $L_a = 1$ y $L_b = 1$ al mismo tiempo (_i.e._ que actualices los registros $A$ y $B$ en una misma iteración).

Entonces, con los _opcodes_ podemos usar menos bits para representar una combinación de señales de más bits (en el computador básico tenemos un total de 12 bits en señales de control, pero solo 7 bits para representar un _opcode_).

¡Espero que se entienda! Saludos. :)

**Comment by rosariodominguezm** [comment]
Me quedó clarísimo! Gracias!
