### ISSUE TITLE
 [T2] Entrega de Diagramas

### ISSUE THREAD

**Issue by Jpuc1143** [IIC2343/Syllabus-2023-1#123]
Hola, para los diagramas se podría entregar el archivo .drawio aparte en vez de hacerle embed al pdf?

**Comment by frvalenzuela** [comment]
Hola @Jpuc1143 !

Por temas de corrección y manejo en Canvas, tiene que estar todos los diagramas incorporados en pdf.

Saludos!

**Comment by Geeermy** [comment]
Como complemento: puedes exportar directamente el diagrama como imagen (PNG por ejemplo). No debería ser complicado incorporar el diagrama en ese caso. :)

¡Saludos!
