### ISSUE TITLE
T2P3 error CMP emuWindows

### ISSUE THREAD

**Issue by JoseTomasSoto** [IIC2343/Syllabus-2023-1#124]
Hola, cuando hago CMP A, (variable)
emuWindows me sugiere error, porque podrá ser? No ejecuta la accion que debe.

No tira error cuando se hace CMP A, variable

**Comment by Geeermy** [comment]
¡Hola!

emuWindows se rige por la ISA del computador básico del curso. En este caso, esta es la tabla de la instrucción `CMP`:

<img width="920" alt="Captura de Pantalla 2023-04-27 a la(s) 09 32 01" src="https://user-images.githubusercontent.com/5559611/234877752-6892f25f-6049-4b71-9224-c09d5d480ac4.png">

Entonces, te tira error `CMP A,(variable)` porque no existe como instrucción. `CMP A,variable` sí te lo toma porque se interpreta como `CMP A,Lit` (en este caso, `Lit` será la dirección de memoria de tu variable, no su valor contenido). Es lo mismo que hacer `MOV A,variable`, donde se interpreta como `MOV A,Lit` con `Lit` igual a la dirección de `variable`.

¡Saludos!
