### ISSUE TITLE
[T2 - P2.d] Duda CALL

### ISSUE THREAD

**Issue by sebacarrasco** [IIC2343/Syllabus-2023-1#125]
Hola, no me termina de quedar claro de dónde debería sacarse la dirección a la que se debe saltar con la instrucción CALL. ¿Debería saltar a la dirección que indica el tope del stack o ingresar como literal la instrucción a la que quiero saltar?

**Comment by Geeermy** [comment]
¡Hola!

Debe ser el literal, al igual que el `CALL` del computador básico. :)

¡Saludos!
