### ISSUE TITLE
[Proyecto] Duda: librería

### ISSUE THREAD

**Issue by pedroriosg** [IIC2343/Syllabus-2023-1#126]
Hola! Quería saber como puedo usar la librería `iic2343`.

Si mi código en `python` guarda en una lista todos los lit + opcode (36 bits) que tengo que escribir en la `ROM`, en orden, ¿cómo puedo usar el `Basys3().write(...)?`

Muchas gracias

**Comment by R0W5tortion** [comment]
Hola. Primero que nada, perdón por la tardanza. 

Como dice en la documentación, `write` recibe dos parámetros: un `int` con la dirección de memoria, y un `bytearray` de largo 5 con el lit+opcode. Ojo con que 5 bytes contienen 40 bits, 4 más que el lit+opcode, para que no se "corran" al hacer el bytearray. El primer byte no puede ser mayor a F (o 15), porque sus 4 bits más significativos siempre son zeros.

_Hint:_ para construir un bytearray hay varias formas, así que procuren revisar su documentación o el `help(bytearray)` en consola. En particular, hay dos formas que probablemente sean las que usen la mayoría de ustedes.
