### ISSUE TITLE
[Proyecto] Duda: ejemplos archivos txt

### ISSUE THREAD

**Issue by pedroriosg** [IIC2343/Syllabus-2023-1#127]
Hola! Quería saber si existe alguna carpeta con programas en assembly que podamos utilizar para corroborar que el assembler funciona bien. También quería preguntar si en las salas de ayuda vamos a poder tener acceso a testear el assembler en la placa con los archivos con que se va a corregir la entrega (para saber si de esta manera estamos ok con el assembler).

Desde ya muchas gracias

**Comment by R0W5tortion** [comment]
Hola! Perdón por la demora. No hay una carpeta con programas, pero en el enunciado de la etapa 2 hay algunos programas de ejemplo que pueden usar. Por otro lado, desafortunadamente no les podemos pasar los archivos que usaremos en la corrección, pero si logran correr los programas de ejemplo no deberían tener problemas

Saludos y mucho éxito
