### ISSUE TITLE
[T3 - P1.b] Duda numeros negativos

### ISSUE THREAD

**Issue by mjadresic** [IIC2343/Syllabus-2023-1#128]
Hola, dentro de los inputs (N) con los que se nos va a evaluar, considerarán los números negativos?
Por ejemplo N=-7 
Entiendo que un numero negativo no puede ser primo (y por ende tampoco gemelo) ya que es divisible por 1, -1 y si mismo, pero mi código se cae al pasarle números negativos de entrada y no se si debe ser aprueba de eso.

**Comment by mjadresic** [comment]
ya no importa, corregi mi codigo pero no me deja borrar el issue

**Comment by Geeermy** [comment]
¡Hola! No te preocupes, deja tu _issue_ abierta ya que le puede servir a alguien más.

Es fácil controlar el caso, pero de todas formas nos enfocaremos en números positivos (mayores o iguales a 1).

¡Saludos!
