### ISSUE TITLE
[T3 - P1.c] Duda output ejemplo

### ISSUE THREAD

**Issue by sperezmasri** [IIC2343/Syllabus-2023-1#129]
Hola, en el ejemplo que se hace con N = 15, según lo que entiendo el output debería ser 7066, 1, 2, 80, 4, 80, 70...  en vez de 7066, 1, 2, 80, 4, 80, 6... Lo que cambié fue el 6 por 70, ya que 6 es divisible por 3, entonces deberíamos guardar un 70 y no el numero mismo. Quería saber si esto es así y fue un error de enunciado o hay algo que yo no estoy entendiendo, gracias 😄.

**Comment by Geeermy** [comment]
¡Hola!

Toda la razón. Solo es un error del enunciado. Lo corregiremos. :)

¡Un abrazo!

**Comment by josefinacortes** [comment]
Hola! Respecto a esto, ser primo gemelo tiene prioridad por sobre todo lo otro? (Ser divisible por 3, 5 y ambos?). Porque, o sino, 3 y 5 deberían ser 70 y 66 y no 80 o no? Muchas gracias!

**Comment by Mamunoz42** [comment]
Me sumo a esta pregunta, no me queda claro cual es la prioridad que debe existir @Geeermy

**Comment by Geeermy** [comment]
@josefinacortes @Mamunoz42 ¡Disculpen la demora! Juré haber contestado.

En el caso puntual de los números 3 y 5 tiene prioridad el hecho de que son primos gemelos. Este caso ocurrirá solo con estos números dado que cualquier otro número que sea divisible por 3 o 5 no será primo por definición.

¡Saludos!
