### ISSUE TITLE
[Proyecto] Duda JLE y JCR

### ISSUE THREAD

**Issue by pedroriosg** [IIC2343/Syllabus-2023-1#130]
Hola! Qué en el enunciado de la Etapa 2 se agregan las instrucciones `JLE` y `JCR`.

Las dos se definen como `carga Ins en PC Ins si en el status...`

Quería saber por qué es `carga Ins en PC Ins` y no `carga Ins en PC si el status...` como en los demás `jumps`, o si es un error de tipeo

Desde ya muchas gracias

**Comment by R0W5tortion** [comment]
Hola!

Esto simplemente es un typo, todos los jumps se comportan igual (aparte de los diferentes flags a los que reaccionan). Perdon por las molestias
