### ISSUE TITLE
[T3 - P1.d] Declaración de Variables

### ISSUE THREAD

**Issue by jrvalenzuela** [IIC2343/Syllabus-2023-1#131]
No se si está demás la pregunta, pero prefiero asegurarme: ¿Se pueden declarar como variables arreglos cuyo largo dependa del número del número de nodos?

**Comment by Geeermy** [comment]
¡Hola!

Lamentablemente, esto complejizaría bastante la corrección, así que no podemos permitir que lo hagas... "directamente". Lo que sí puedes hacer es definir la variable de forma **dinámica**. Por ejemplo, fíjate en la variable de _output_ `out` de la pregunta 1.3. En el fondo, ahí lo que se les pide es que definan una variable que es dinámica porque le van añadiendo valores durante la ejecución del programa. Entonces, sí tienes permitido definir una variable auxiliar dinámica que sea el arreglo de nodos y que, al principio del programa, se complete dinámicamente según el argumento `N`. Ojo que tendría que ser la última que definas en el segmento `.data` para que no sobreescriba el resto de variables.

Espero que se entienda. :)

¡Saludos!

**Comment by Geeermy** [comment]
@sperezmasri  ¡Hola! Puedes definir más de una o las que necesites. :)

¡Saludos!

**Comment by sperezmasri** [comment]
Ok, entiendo que se puede hacer, pero me queda la duda de cómo hacer para que una variable no sobrescriba a la otra

**Comment by Geeermy** [comment]
@sperezmasri Puedes definir dos de forma consecutiva con la directiva `.space` para reservar cierta cantidad de Bytes de memoria, para después ir completándolas según los largos de tus arreglos. :) Puedes guardar espacio arbitrariamente grande si lo necesitas para irte a la segura (500 bytes por arreglo debiese ser más que suficiente, no haremos _tests_ con arreglos muy grandes).

Lo que más nos interesa es que para esta pregunta no _hardcodeen_ el tamaño de dichas listas complementarias según la cantidad de nodos, ya que dificultaría la corrección.

¡Saludos!

**Comment by sperezmasri** [comment]
Ah ok muchas gracias, así mismo lo tenía implementado :smile:
