### ISSUE TITLE
[T3 - P1.a] Aclaración pregunta

### ISSUE THREAD

**Issue by Dafnemami** [IIC2343/Syllabus-2023-1#132]
Hola!,

No sé si estoy entendiendo perfectamente la pregunta. Prefiero preguntar antes de invertir tiempo en algo incorrecto. Me podrían aclarar que solicitan? 

Saludos!!
🏎

**Comment by tocococa** [comment]
Hola @Dafnemami podrías por favor indicar con qué elementos particulares de la pregunta tiene dudas?

**Comment by Dafnemami** [comment]
@tocococa Creo que me enredé en una tontera, al final solo están preguntando por  "qué indica la convención de llamada para la extensión base RV32I"? Es que el preámbulo de la pregunta me enredó, no entendí para qué mencionaron que "que a partir de la
versión V20191213 se encuentra definida como parte del psABI" 

Me explico?

**Comment by tocococa** [comment]
Antiguamente la convención de llamada venía en el manual de la ISA (que aparece como lo primero si lo googlean), pero a partir de esa versión está definida en el Processor-specific application binary interface (psABI), y deberían guiarse a partir de esa referencia.

**Comment by mmrodriguez5** [comment]
A partir de esa comparamos los cambios que se hicieron en la nueva versión?
