### ISSUE TITLE
[T3 - P1.d] Duda tipos de grafos a evaluar

### ISSUE THREAD

**Issue by mjadresic** [IIC2343/Syllabus-2023-1#133]
Hola, mi duda es si nos van a evaluar solamente con grafos "cuadrados" (2x2, 3x3, 4x4) conectados de la misma forma que el ejemplo del enunciado y/o cambiando las posiciones de los nodos 1,2,3, o se evaluara con distintos tipos de grafos (por ejemplo, un árbol). Mi duda surge ya que para implementar un algoritmo de búsqueda seria muy útil saber "a prueba de que" tipo de grafo debe ser, por ejemplo, para saber como incluir backtracking.

**Comment by frvalenzuela** [comment]
Hola @mjadresic !

No serán evaluados solo con grafos cuadrados. Puede ser con distintos tipos de grafos.

Saludos!
