### ISSUE TITLE
[T3 - P2b] Python 3.10 o superior

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2343/Syllabus-2023-1#135]
Hola, estaba intentando hacer la pregunta 2b y me surgió un error de sintaxis para `coprocessor.py` de un código que no he tocado. Adjunto imagen.

![image](https://github.com/IIC2343/Syllabus-2023-1/assets/48535635/7870442d-df02-466e-a8b1-a30f17b21f7b)

**Comment by tocococa** [comment]
Hola @ignacioarteaga99, tienes que usar Python 3.10 o superior, como sale indicado en el README.

**Comment by ignacioarteaga99** [comment]
> 

Hola! Sí! De hecho actualicé la versión que tenía en mi PC. ¿Tal vez es porque el VSCode está utilizando la version antigua? ¿O no tiene nada que ver? ¿Cómo podría ver eso?

**Comment by tocococa** [comment]
Si estás corriendo desde VSCode, abajo a la derecha tienes que elegir el runtime, en tu barra de estado abajo a la derecha sale Python 3.9.7, deberías poder hacerle click ahí y cambiar a Python 3.10 u otra versión.

**Comment by ignacioarteaga99** [comment]
Intenté realizarlo con python 3.10 e incluso python 3.11.3 y aún me tira el mismo error :(

**Comment by tocococa** [comment]
Puedes correrlo desde una terminal externa a la de vscode y asegurarte que está ejecutando con Python 3.10?

**Comment by ignacioarteaga99** [comment]
Pude solucionarlo, gracias!
