### ISSUE TITLE
[T3 P2.b] Cinta magnética

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2343/Syllabus-2023-1#136]
Hola, entiendo que cuando se lee la cinta magnética a partir de la posición `data` obtenida del dispositivo `entropy`, debería obtener valores numéricos de esta. Sin embargo, el archivo de esta tape (tape1.tape.txt) es un `string`, por lo que obtengo letras. 

No sé si eso es parte de la pregunta y hay que saber manejarlo o es un error y en realidad dicho archivo deberían ser números.

Si efectivamente es un texto, no entiendo cómo manejar eso y qué debería hacer para que sean números y poder operar con ellos. 
Desde ya muchas gracias.

**Comment by tocococa** [comment]
Hola @ignacioarteaga99 , el comportamiento que describes es el esperado, si necesitas usar un carácter como un número puedes usar su valor ASCII.

**Comment by ignacioarteaga99** [comment]
Okey gracias! Y en ese sentido, ¿debería leer un sólo bit de la cinta magnética por cada posición entonces? Perdón lo perdido, es que no entiendo muy bien que es ASCII ni cómo se usa

**Comment by ignacioarteaga99** [comment]
También me entra la de cómo usar el valor ASCII del carácter o si existe alguna componente en el programa que realice dicha traducción, ya estaba revisando esta página https://ascii.cl/es/ y son varios símbolos. 

Feliz si me ayudas con esas dudas porque no entiendo mucho qué esperan de nosotros en esa parte de la pregunta y cómo quieren que manejemos eso.

Gracias!

**Comment by tocococa** [comment]
Hola @ignacioarteaga99, la cinta magnética recibe como input pares de dígitos y los escriba en la "cinta" con su representación ASCII. Las funciones `ord()` y `chr()` te pueden ayudar a trabajar en esa parte.

**Comment by tzehnder** [comment]
Hola, tengo una duda tambien pero con la cantidad de bytes a leer en la cinta magnetica, nos dicen en el enunciado que el data obtenido del entropy es la posicion de donde obtendremos los numeros de la cinta, pero como se cuantos bytes son los que utilizar para el numero? por lo que entendi del readme es algo que hay que entregarle a la cinta. 
se me ocurrio que debiesemos usar entropy para eso tambien, pero no estoy seguro.
Una duda extra es si para obtener dos numeros distintos debo hacer entropy mas de una vez, para cada numero, y si es asi debiese eliminar el SEED que esta en entropy o no?

**Comment by tocococa** [comment]
Hola @tzehnder, basta con que lean algo que tenga sentido para lo que se les pide a continuación en la tarea. Deja el SEED donde está al momento de entregar, pero si quieres mientras pruebes lo puedes cambiar o comentar.

**Comment by Mamunoz42** [comment]
A que se refieren con algo que tenga sentido, es decir debo fijarme en que el texto que leo de la cinta tenga logica?
Porque se me ocurre hacer que la cantidad de bytes que leo sea el mismo numero aleatorio que recibo, pero no se si esto es lo esperado

**Comment by tocococa** [comment]
No que tenga sentido el texto mismo, pero que la secuencia de instrucciones haga algo que tenga algo de sentido.
