### ISSUE TITLE
[T3 P2.b] Posible error de código coprocessor.py

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2343/Syllabus-2023-1#137]
Hola, estaba realizando esta parte de la tarea y estaba realizando la operación `OUT(8, 0)` de modo de cargar en el registro `OP` la operación de suma de los valores de los registros A y B. 
Hasta ahí todo bien. Pude debuggear y confirmar que los valores se guardaban de buena manera en los registros y que también pasaba lo mismo con la operación. Sin embargo, cuando se procede a realizar `IN(9)`, en el caso de la suma, ocurre un problema que no pasa por los otros casos (pude corroborarlo al aplicar la resta), y es que al ser 0 el valor que se le entrega al `registers["OP"]`, no se realiza la operación al activarse esta restricción (líneas 28 - 31 del `coprocessor.py`):
```
def __run(self) -> None:
        if not self.registers["OP"]:
            logging.debug(f'OP register not set')
            return None
```
Y en el `pmio.logs` se lee:
```
DEBUG:root:OP register not set
```
Como señalaba anteriormente, este error no ocurre al realizar otro tipo de operaciones; me imagino que es porque los valores son distintos de `0`.

Desde ya muchas gracias y quedo atento a la resolución de esta `issue`.

**Comment by tocococa** [comment]
Hola @ignacioarteaga99 ya está arreglado, gracias por avisar!
