### ISSUE TITLE
[T3 - P1.d] Duda matriz de adyacencia ejemplo

### ISSUE THREAD

**Issue by sperezmasri** [IIC2343/Syllabus-2023-1#138]
Hola, me surgió una duda con el ejemplo del enunciado de la preguna 1d. La tercera fila de la matriz es la siguiente: 0 1 0 0 1 1 0 0 0, esto esta indicando que el nodo 3, puede ir al nodo 2, 5, y 6, me queda la duda de si realmente puede ir al nodo 5, ya que este movimiento sería diagonal. También la última fila (nodo 9) es la siguiente: 0 0 0 0 0 0 1 0 1, lo que indica que el nodo 9 puede ir al nodo 7 y 9, creo que debería estar conectado a los nodos 6 y 8 según entiendo. No se si es error de enunciado o yo estoy considerando algo mal, gracias 😄

**Comment by tocococa** [comment]
Hola! Sip, la matriz está mal anotada, guíate por el dibujo para ver el puzzle, lo vamos a corregir, gracias.
