### ISSUE TITLE
Proyecto - ejemplo programa 8

### ISSUE THREAD

**Issue by fedezang** [IIC2343/Syllabus-2023-1#139]
Hola! tengo una duda del programa 8 de ejemplo en el enunciado. Está la instrucción MOV B,arr . Pero entiendo que la instrucción debería ser en realidad MOV B, (arr) para utilizar bien la notación. ¿Es un error o hay que considerar los casos en que están escritas así las instrucciones? (para saber diferenciar entre MOV A,(dir) y MOV A,Lit por ejemplo)

**Comment by R0W5tortion** [comment]
Hola! El uso de `arr` es solo una conveniencia para quien hace el programa en Assembly. Lo primero que hace el ensamblador es transformar ese `arr` en el número que corresponde a su dirección en memoria, que en este caso es `0`. Entonces, la instrucción `MOV B,(arr)` efectivamente sería una instrucción de tipo `MOV B,(dir)`, mientras `MOV B,arr` es en realidad de tipo `MOV B,Lit`

**Comment by fedezang** [comment]
Perfecto entiendo.
Entonces la instrucción debería haber sido MOV B, (arr)?   (faltaban los paréntesis)

**Comment by Geeermy** [comment]
¡Hola Federico! Disculpa que me meta jeje.

No, está bien la instrucción. Cuando usamos el formato `MOV B,arr` en vez de `MOV B,(arr)`, lo que decimos es que `B` tendrá la **dirección de memoria** del arreglo (y no su contenido). Si usaras `MOV B,(arr)`, en este caso se te cargaría en el registro B **el valor del primer elemento del arreglo en vez de su dirección de memoria. Por eso, si te fijas más abajo, podrás notar que el registro B se utiliza para recorrer el arreglo con direccionamiento indirecto.

En resumen: Sí debes considerar las instrucciones del tipo `MOV A,dir` y `MOV B,dir`. En la práctica se traducirán al _opcode_ de la instrucción `MOV A,Lit` o `MOV B,Lit` (siendo el literal la dirección de memoria de la variable en este caso).

¡Avísame si sigues con dudas!

**Comment by fedezang** [comment]
Perfecto. Osea en un caso como
DATA:
arr 5
     6
CODE:
MOV B,(arr) // mueve 5 al registro B
MOV B,arr // mueve 0 al registro B
Seria esto?

Esto solo aplica para la instrucción MOV?

**Comment by R0W5tortion** [comment]
Exacto. Si te fijas en el mismo programa usa la instrucción `MOV A, (B)` para recuperar elementos del arreglo, por lo mismo

**Comment by fedezang** [comment]
Gracias!
