### ISSUE TITLE
[T1 - P1 .C] Bases numéricas

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2343/Syllabus-2023-1#14]

**Comment by Geeermy** [comment]
¡Hola Pablo!

En resumen, sí. Supongamos que tomamos $K = 3$, $N = 2$ y $T = 1$. Tendríamos las bases $K^N = 3^2 = 9$ y $K^T = 3^1 = 3$. En este ejemplo, buscamos un algoritmo eficiente para transformar un número base 9 (que utiliza dígitos 0, 1, 2, 3, 4, 5, 6, 7, 8) a base 3 (que utiliza dígitos 0, 1, 2). Al final lo que planteas es solo un caso puntual y lo que pedimos es su generalización.

¡Espero que se entienda!

**Comment by pabloalvarez67** [comment]
Si perfecto! hice ese ejemplo para que se entienda mi punto. Gracias!

**Comment by Geeermy** [comment]
Dejemos las _issues_ abiertas hasta que termine la tarea porque le pueden servir a más personas. 😄
