### ISSUE TITLE
[Proyecto] - etapa 2 y overflow 

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2343/Syllabus-2023-1#141]
Hola! Tengo una duda respecto a la etapa 2 del proyecto. Según entiendo por enunciado, aún no deberíamos agregar las componentes necesarias para detectar saltos condicionales por excepción (tipo overflow), sin embargo, quería confirmar que esto fuera así o si, en realidad, sí debemos incorporarlos para esta entrega. 
Desde ya muchas gracias!

**Comment by R0W5tortion** [comment]
Hola! Los saltos condicionales que tienen que implementar son los relacionados con las señales C, N, Z que ya tienen en la ALU. Las otras flags no se implementan en el proyecto

Saludos

**Comment by ignacioarteaga99** [comment]
> Hola! Los saltos condicionales que tienen que implementar son los relacionados con las señales C, N, Z que ya tienen en la ALU. Las otras flags no se implementan en el proyecto
> 
> Saludos

Muchas gracias!
