### ISSUE TITLE
[Proyecto] - Uso de librería

### ISSUE THREAD

**Issue by fedezang** [IIC2343/Syllabus-2023-1#143]
Hola!
Quería pedir un poco de ayuda con la libreria que hay que ocupar.
Para el método rom_programmer.write(0, bytearray([0x0, 0x00, 0x30, 0x16, 0x01]))
esos números que están en hexadecimal, tendría que pasarlos a decimal para escribir en el bytearray? O cómo puedo escribir el bytearray?

**Comment by R0W5tortion** [comment]
Hola!
Cuando haces `0x16`, lo que se genera es un `int` con valor de 22 (esto lo puedes comprobar por tu cuenta en una consola Python si quieres). Internamente, un `int` se guarda como un binario (en estricto rigor son bytes, al igual que todo lo que se guarda en un computador), pero se _muestra_ como decimal cuando haces un print o lo pasas a string. Lo que esto significa es que no necesitas preocuparte de pasarlo a decimal

Ahora bien, para generar un bytearray hay varias formas, pero la que se usa en ese ejemplo es "a partir de una lista de ints". También se puede crear uno de largo 5 rellenado con zeros y reemplazar cada byte con `bytearray[i] = x`, dondo `x` es un `int` en el rango `0 <= x <= 255`, o crear uno vacío e ir agregando con `bytearray.append(x: int)`. La otra es, teniendo un `int` grande, pasarlo primero a bytes con `b = x.to_bytes(length: int, endianness)`, donde `length` es la cantidad de bytes y la `endianness` puede ser `big` o `little` (probablemente usen `big`), y luego hacer simplemente `bytearray(b: bytes)`

Espero te haya servido, si algo no te quedó claro pregunta con confianza :)
