### ISSUE TITLE
[T3 - P1.c] Duda codigo

### ISSUE THREAD

**Issue by martin-santiago** [IIC2343/Syllabus-2023-1#144]
Hola, para las preguntas que son resolver mediante codigo, basta con ir dejando comentarios por encima sobre para que es cada instruccion?, o debo tambien hacer una explicacion detallada en el pdf

**Comment by tocococa** [comment]
Hola @martin-santiago, para las preguntas en que se pide código basta que indiques con comentarios que va haciendo el código,  no es necesario que incluyas documentos extra.
