### ISSUE TITLE
[Proyecto] Duda: sobre el informe

### ISSUE THREAD

**Issue by pedroriosg** [IIC2343/Syllabus-2023-1#145]
Hola,

En el enunciado se pide un informe que contenga el código de máquina correspondiente. Esto se refiere a las especificaciones de cómo hicimos el assembler? (ya que no hay un código de máquina propiamente tal como en la E1)

Saludos

**Comment by R0W5tortion** [comment]
Hola

Con "código de máquina correspondiente" nos referimos al binario de 36 bits que corresponde a cada instrucción (o _los_ binarios si es más de uno), no a lo que esté _hardcodeado_ en la ROM como en la entrega 1.

Saludos

**Comment by pedroriosg** [comment]
Entiendo, pero eso no iría en la parte de adjuntar la tabla con los opcodes?

**Comment by R0W5tortion** [comment]
Pueden hacer una tabla y referenciarla dentro del informe o pueden dejar la tabla en el mismo informe (o pueden hacer ambos). Lo importante es que esa tabla exista y, si no está en el informe, que este diga dónde encontrarla
