### ISSUE TITLE
[T3 - P1.c] Duda output esperado

### ISSUE THREAD

**Issue by jrvalenzuela** [IIC2343/Syllabus-2023-1#146]
¿Se debe imprimir un output para esta pregunta o basta con que la secuencia esté guardada en la dirección  `out`?

**Comment by tocococa** [comment]
Hola @jrvalenzuela, para el output baste que lo dejen guardado en la dirección de `out` siempre y cuando este resultado quede legible desde el visor de memoria del emulador, de lo contrario pueden imprimirlo con una `ecall`.
