### ISSUE TITLE
[T3 - P1.c] Duda output

### ISSUE THREAD

**Issue by srodriguezp** [IIC2343/Syllabus-2023-1#147]
¿La etiqueta out necesariamente tiene que ser .word o la podemos cambiar por .space o .word 0:N-1? Esto porque estoy complicado guardando los valores en cada iteración.

**Comment by Geeermy** [comment]
¡Hola!

No hay problema. Cámbialo con tal de que el resultado quede almacenado en memoria. De forma complementaria, puedes imprimirlo en consola para verificar. :)

¡Saludos!
