### ISSUE TITLE
[T3 - P1.b] Duda enunciado

### ISSUE THREAD

**Issue by francoschiaffino** [IIC2343/Syllabus-2023-1#148]
Hola! El número a evaluar necesariamente es primo o puede no serlo?

**Comment by juanluis2019** [comment]
Hola! Dos preguntas: 1. ¿Para la solución de esta pregunta se debe necesariamente usar un algoritmo recursivo? 2. ¿Para la solución de esta pregunta es obligatorio respaldar valores en el stack?

**Comment by Geeermy** [comment]
¡Hola!

1. No.
2. Si no realizas llamadas a subrutinas, no, ya que no tendrías una convención de llamada que cumplir.

¡Saludos!
