### ISSUE TITLE
[Proyecto] Duda uso de la libreria

### ISSUE THREAD

**Issue by srodriguezp** [IIC2343/Syllabus-2023-1#149]
Al usar rom_programmer.begin() en el código del assembler me tira este error: iic2343.errors.InvalidPortError: 3 serial ports present, please select one. ¿Cómo selecciono el puerto de la Basys? ¿o que otro problema podría estar ocurriendo?

**Comment by frvalenzuela** [comment]
Hola @srodriguezp !

De la siguiente forma:

```
from iic2343 import Basys3

instance = Basys3()

instance.begin(port_number=2)  # port_number is optional
instance.write(1, bytearray([0x00, 0x00, 0x10, 0x16, 0x01]))
instance.write(2, bytearray([0x00, 0x00, 0x00, 0x18, 0x03]))
instance.write(3, bytearray([0x00, 0x00, 0x20, 0x18, 0x03]))
instance.write(4, bytearray([0x00, 0x00, 0x00, 0x20, 0x00]))
instance.end()
```

Para más información revisar: https://pypi.org/project/iic2343/

¡Saludos!
