### ISSUE TITLE
[T3 - P1.c] Duda print

### ISSUE THREAD

**Issue by srodriguezp** [IIC2343/Syllabus-2023-1#150]
¿Cómo se pueden separa los prints por ',' o mostrarlos en consola en diferentes líneas para mejorar la lectura del ouput?

**Comment by Geeermy** [comment]
¡Hola!

No es estrictamente necesario que te preocupes por eso, pero lo que puedes hacer es [ver la documentación de system calls de RARS](https://github.com/TheThirdOne/rars/wiki/Environment-Calls) y utilizar la que realiza la impresión de un _string_ (`PrintString`). Ojo que en `a0` debes guardar la dirección del string, no el valor (utilizando la instrucción `la a0, var`).

¡Avísame si te sirve!

**Comment by jrvalenzuela** [comment]
Sobre el mismo tema, entonces se puede declarar una variable que almacene `" "` en la parte de .data para poder separar los enteros cuando se imprimen? o esa parte tiene que ser si o si como está en el enunciado?

**Comment by Geeermy** [comment]
@jrvalenzuela puedes agregarlo, no hay problema. :)

**Comment by jrvalenzuela** [comment]
gracias
