### ISSUE TITLE
[Proyecto] Instrucción no válida en Test 2

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2343/Syllabus-2023-1#151]
Hola!

Me encontraba revisando el Test 2 que se subió para poder probar nuestro computador y Assembler, y una de las instrucciones que se indica no es válida para la arquitectura de nuestros computadores, además en el enunciado no se especifica la instrucción.

Adjunto una imagen mostrando cual es la línea (`177`) en la que se encuentra la instrucción no válida.

Si es que lo que digo no es correcto, cual es la razón por la que esto sería válido y a que instrucción correspondería.

<img width="176" alt="Screenshot 2023-05-26 at 11 25 53" src="https://github.com/IIC2343/Syllabus-2023-1/assets/62019329/863b31ae-a3ac-4918-8340-7db035e086b6">

**Comment by frvalenzuela** [comment]
La instrucción que hace referencia es la instrucción `MOV (B), Lit` que adjunto en la tabla de la etapa 2:

<img width="723" alt="image" src="https://github.com/IIC2343/Syllabus-2023-1/assets/20147482/3f307f60-eeec-4f9b-ba54-af3c1276ad0d">


Donde el literal esta manejado como t0 que es un dirección de la RAM que debe ser aceptado según se establece en el enunciado de assembler que adjunto a continuación un fragmento:

<img width="798" alt="image" src="https://github.com/IIC2343/Syllabus-2023-1/assets/20147482/4e2b10de-064f-4afd-b503-cb7da7af19b4">


Recomiendo también revisar también la issue #139  que habla sobre esto en más en detalle.

Saludos!

**Comment by martin-santiago** [comment]
Hola, esto aplica para todos las intrucciones que tengan Lit? o solo a las de tipo `MOV`?

por ejemplo, no veo mucho sentido a 

`ADD A, t0`  que sumria el valor en el regA con la direccion de memoria de t0

**Comment by R0W5tortion** [comment]
Efectivamente, en cualquier instruccion con Lit, este puede ser reemplazado por el nombre de una variable

**Comment by frvalenzuela** [comment]
Hola @martin-santiago !

Todas las instrucciones que contengan el nombre de una dirección de memoria. Como la que muestras a continuación

 `ADD A, t0` . Sobre el sentido, eso realmente dependerá del programador y el software implementado. Tener dicha opción  podría ser útil en caso que se manejen matrices o tensores por ejemplo.
 
 Saludos!
