### ISSUE TITLE
Duda al usar la biblioteca en el Proyecto

### ISSUE THREAD

**Issue by scagender** [IIC2343/Syllabus-2023-1#153]
Hola, ya terminamos el assembler y se supone que el vivado. Sin embargo, cuando utilizamos la biblioteca que se nos fue pasada para el assembler el codigo solamente nos carga la primera instrucción en la placa y luego nada más. El código como que no avanza más allá de la primera instrucción. Vimos las demás issues, y trabajamos el código como se propone en la documentación, pero no hemos logrado saber que pasa.

Por ejemplo si el codigo assembly es:
MOV A,B
MOV B,A

Solamente carga MOV A,B cuando usamos la biblioteca. Sin el uso de la biblioteca si se reconoce el resto del codigo.

**Comment by frvalenzuela** [comment]
Hola @scagender !

Mi experiencia me dice que puede ser que exista un problema con el ensamblador, dado que la única comunicación que hace la librería es pasar los datos dados del ensamblador a la ROM. Otra opción que se me ocurra es que su programa en python solo este cargando una instrucción, en dicho caso recomiendo revisar el enunciado de assembler que muestra el funcionamiento.

También recomiendo conectar a los displays otras señales, como la saliente de la ROM, su control unit o PC, para verificar que efectivamente solo se esta cargando una instrucción.

Si luego de lo anterior el problema no se soluciona favor comentar por esta issue.

Saludos!
