### ISSUE TITLE
[T3 - P2.b] Utilización variables auxiliares

### ISSUE THREAD

**Issue by PedroDP99** [IIC2343/Syllabus-2023-1#154]
Hola! El enunciado de la pregunta 2 de la tarea dice que debe hacerse uso **exclusivo** con la librería fakeio. Con esto me entro la duda de si pueden utilizarse variables auxiliares, ya que viendo la libería, el comando IN(X) retorna un string (que es importante para el resto). Con variables auxiliares me refiero a algo del estilo:
` data = int(pmio.IN(X))`
 `pmio.OUT(Y,data)`

Quedo atento

**Comment by tocococa** [comment]
Hola @PedroDP99, si, puedes usar variables, control de flujo y todo lo demás, la idea es que no importen nada más aparte de fakeio.

**Comment by PedroDP99** [comment]
Perfecto. Muchas gracias!!
