### ISSUE TITLE
[T3 - P2.b] Orden instrucciones

### ISSUE THREAD

**Issue by PedroDP99** [IIC2343/Syllabus-2023-1#155]
Hola! Me queda una duda con respecto al orden de las instrucciones 2 y 3, ya que en la instrucción 2 se dice que deben realizarse 3 **operaciones** y en la instrucción 3 dice que se debe escribir el resultado de la **operación** al inicio de la cinta magnética. Ahí me entra la duda si el resultado se escribe luego de cada operación, o al terminar las 3 operaciones.
Quedo atento

**Comment by pabloalvarez67** [comment]
Misma duda.

**Comment by tocococa** [comment]
Hola @pabloalvarez67 @PedroDP99 con que escriban el resultado de realizar las tres operaciones seguidas es suficiente.

**Comment by pabloalvarez67** [comment]
> Hola @pabloalvarez67 @PedroDP99 con que escriban el resultado de realizar las tres operaciones seguidas es suficiente.

Pero debemos usar 3 operaciones distintas con los mismo valores que obtenemos de entropy? o debemos usar los resultados de una operación para realizar otra operación?
Por ejemplo, si de entropy obtengo X e Y, debo hacer X+Y, X-Y ,X*Y? o debería usar el resultado de X+Y = Z, para luego hacer Z - X (o Y)?

**Comment by Mamunoz42** [comment]
Me surge la misma duda que @pabloalvarez67, no estoy del todo claro.
@tocococa

**Comment by tocococa** [comment]
Hola @Mamunoz42 @pabloalvarez67 eso queda a criterio de ustedes, pero si se fijan como funciona el coprocesador van a ver cuál es la alternativa más simple.
