### ISSUE TITLE
[T3 - P1] Duda sobre cómo correr el emulador

### ISSUE THREAD

**Issue by jpgazmuri** [IIC2343/Syllabus-2023-1#156]
Tengo un mac y no he podido entender bien cómo correr el emulador, cloné el repositorio e intenté correr build-jar.sh pero sigo sin lograr abrirlo, hay algún tutorial para esto?

**Comment by Geeermy** [comment]
¡Hola!

No debes clonar el repositorio, debes descargar el ejecutable `.jar` y ejecutarlo luego de haber instalado Java 8 o superior.

Puedes descargar el ejecutable [aquí](https://github.com/TheThirdOne/rars/releases/tag/v1.6) y ver cómo instalar Java 8 en un Mac M1 [aquí](https://erwinschleier.medium.com/install-jdk-8-and-setup-java-home-on-mac-m1-1b0ea243b05a) (o si no es M1, descargarlo e instalarlo directo de [aquí](https://www.java.com/en/download/manual.jsp)).

Me cuentas si lo logras. :)
