### ISSUE TITLE
[T3 - P2.a] Mret y acciones a ejecutar en estado no deseado

### ISSUE THREAD

**Issue by sebacarrasco** [IIC2343/Syllabus-2023-1#157]
Hola, para esta pregunta partí (fuera de la subrutina) por escribir valores en los registros de estado para así poder probar el funcionamiento de la subrutina que nos piden crear.
El tema es que al intentar correr el código en el emulador, este no me reconoce la instrucción mret. Por lo mismo me queda la duda si se va a correr el código (en cuyo caso quizás sea necesario reemplazar mret por ret) o si se revisará "a mano".

Mi otra duda es que en el enunciado dice que la subrutina "se encargará de apagar el motor del tren, hacer ruido y mandar un reporte cuando un estado sea no deseado". Entonces, me queda la duda si apagar el motor y hacer ruido se hacen solo cuando es un estado no deseado o siempre.

**Comment by Geeermy** [comment]
¡Hola!

1. Nosotros nos haremos cargo de ver cómo probarlo, así que puedes dejar `mret` aunque no funcione en el emulador. Lo que hiciste para probarlo está perfecto. :)

2. Esas tres operaciones deben realizarse **juntas** en caso de un estado no deseado (si todos los estados son "deseados", entonces no hay necesidad de apagar el motor, de avisar del problema con un ruido ni de enviar un reporte, ya que el tren puede funcionar normalmente).

¡Saludos!

**Comment by sebacarrasco** [comment]
Muchas gracias!

**Comment by pabloalvarez67** [comment]
> ¡Hola!
> 
> 1. Nosotros nos haremos cargo de ver cómo probarlo, así que puedes dejar `mret` aunque no funcione en el emulador. Lo que hiciste para probarlo está perfecto. :)
> 2. Esas tres operaciones deben realizarse **juntas** en caso de un estado no deseado (si todos los estados son "deseados", entonces no hay necesidad de apagar el motor, de avisar del problema con un ruido ni de enviar un reporte, ya que el tren puede funcionar normalmente).
> 
> ¡Saludos!

Hola profe! no me queda claro, en un estado no deseado se debe activar el freno de emergencia, notificar a la locomotora y mandar el reporte al mismo tiempo? eso si, la notificacion y el freno son estados de la misma variable de memoria `reg_tr`, entonces no seria como inútil en una misma subrutina o proceso cambiar los valores las 2 veces?
Y respecto al ciclo del programa, una vez que hago esos arreglos, debería volver como al ciclo inicial para chequear que tal están los demás aspectos del tren o no? como la protuberancia y derrame.

Saludos

**Comment by Geeermy** [comment]
¡Hola Pablo!

1. Podría parecer innecesario, pero por ejemplo, por detrás podría haber un esquema de _polling_ que revise si el estado del registro indica que se debe activar el freno de emergencia o no (siendo esta operación de alto riesgo). En ese caso, no es descabellado que este registro maneje estos dos casos. De todas formas, ambos se podrían manejar en registros distintos, pero dado el enunciado simplemente asume que el sistema funciona así (respetando el orden de las acciones eso sí).

2. En **cualquier** estado no deseado querrás que el tren se detenga de inmediato, por lo que no tendría mucho sentido seguir revisando el resto de estados. Deberías terminar la ejecución de la ISR en este caso. Ahora, si te hace más sentido revisar todos los casos antes de realizar las acciones de detención y alerta del tren, puedes hacerlo poniéndolo como supuesto en tu programa (ya sea en un pdf o comentado en el código). Lo importante es que en cualquier caso siempre termines por retornar, no que se quede revisando iterativamente hasta el infinito.

¡Saludos!

**Comment by pabloalvarez67** [comment]
> ¡Hola Pablo!
> 
> 1. Podría parecer innecesario, pero por ejemplo, por detrás podría haber un esquema de _polling_ que revise si el estado del registro indica que se debe activar el freno de emergencia o no (siendo esta operación de alto riesgo). En ese caso, no es descabellado que este registro maneje estos dos casos. De todas formas, ambos se podrían manejar en registros distintos, pero dado el enunciado simplemente asume que el sistema funciona así (respetando el orden de las acciones eso sí).
> 2. En **cualquier** estado no deseado querrás que el tren se detenga de inmediato, por lo que no tendría mucho sentido seguir revisando el resto de estados. Deberías terminar la ejecución de la ISR en este caso. Ahora, si te hace más sentido revisar todos los casos antes de realizar las acciones de detención y alerta del tren, puedes hacerlo poniéndolo como supuesto en tu programa (ya sea en un pdf o comentado en el código). Lo importante es que en cualquier caso siempre termines por retornar, no que se quede revisando iterativamente hasta el infinito.
> 
> ¡Saludos!

Gracias profe! comprendo. Para efectos de esta pregunta, es válido ingresar a las subrutinas usando CALL?

**Comment by Geeermy** [comment]
Si te refieres a las subrutinas que revisan cada registro, sí. De hecho, esa es **la forma** de hacerlo (usar jumps no es realmente usar subrutinas).

¡Saludos!
