### ISSUE TITLE
[T3 - P1.d] Asumir grafos no dirigidos

### ISSUE THREAD

**Issue by illanes00** [IIC2343/Syllabus-2023-1#158]
Hola! Tal como dice el título, quería preguntar si podemos asumir que los gráficos no son dirigidos, es decir, si puedo pasar del nodo X al nodo Y, también puedo pasar del nodo Y al nodo X

Gracias de antemano!

**Comment by tocococa** [comment]
Hola @illanes00. los grafos son no dirigidos, de todas formas si te fijas en las matrices de adyacencia que les dimos están las aristas para ambas direcciones, si hay un 1 en i,j también hay uno en j,i.

**Comment by illanes00** [comment]
Muchas gracias @tocococa !
