### ISSUE TITLE
[T3 - 2-B] Duda printer

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2343/Syllabus-2023-1#159]
Hola! no me queda muy claro que es lo que debo printear en el programa.
Se supone que debo hacer  print a los 3  resultados de las operaciones?
Lo otro, me ocurre que tengo el siguiente error intentando imprimir el resultado de una suma:
OverflowError: Python int too large to convert to C int

No sé si debe de haber una forma específica de manipular los  textos para transformarlos a ascii para que estos errores no ocurran? 

Gracias de antemano.

**Comment by tocococa** [comment]
Hola @pabloalvarez67, basta con que vayas haciendo print de lo que leas/escribas, aunque igual se debería poder ver en los logs. Sobre el error, sin más contexto del que entregas no sabría decirte que puede estar pasando.

**Comment by pabloalvarez67** [comment]
Intento hacer:
pmio.OUT(0, result)
Siendo result la suma de los números aleatorios que me dió el entropy. Es un número bastante grande, por eso yo creo que me tira el OverflowError.
De ahí también surge mi otra duda, si es que hay alguna forma en específica para traspasar los textos aleatorios a formato ascii para que no ocurran estos errores.

**Comment by tocococa** [comment]
Para castear de ASCII a int o viceversa, tienes los métodos `ord()` y `chr()`. El error de overflow probablemente ocurre por lo que estás diciendo.

**Comment by Geeermy** [comment]
¡Hola Pablo!

En ese caso puedes aplicar una operación módulo (%) para asegurarte que el número siempre esté en un rango válido de códigos ASCII. Con eso basta. :)

¡Saludos!

**Comment by pabloalvarez67** [comment]
> ¡Hola Pablo!
> 
> En ese caso puedes aplicar una operación módulo (%) para asegurarte que el número siempre esté en un rango válido de códigos ASCII. Con eso basta. :)
> 
> ¡Saludos!

Vale profe, y en caso de no estar en un rango válido, debería omitir ese resultado y pasar a otra operación?

Gracias!

**Comment by Geeermy** [comment]
La idea es que lo uses de alguna manera, porque podría pasar que todas las operaciones te den números inválidos en ASCII.

Si nos guiamos por [esta referencia](https://www.w3schools.com/charsets/ref_html_ascii.asp), podrías hacer que tu número pase a ser siempre válido en un intervalo ASCII. Por ejemplo:

```
ascii_result = operation_result % 127
```

Esto te asegurará que tu número siempre esté en el rango 0-126 y, por ende, que siempre pueda ser interpretado como ASCII.

¡Saludos!

**Comment by pabloalvarez67** [comment]
> La idea es que lo uses de alguna manera, porque podría pasar que todas las operaciones te den números inválidos en ASCII.
> 
> Si nos guiamos por [esta referencia](https://www.w3schools.com/charsets/ref_html_ascii.asp), podrías hacer que tu número pase a ser siempre válido en un intervalo ASCII. Por ejemplo:
> 
> ```
> ascii_result = operation_result % 127
> ```
> 
> Esto te asegurará que tu número siempre esté en el rango 0-126 y, por ende, que siempre pueda ser interpretado como ASCII.
> 
> ¡Saludos!

Muchas gracias profe! se pasó.
Saludos!
