### ISSUE TITLE
[T3 - P2.a] Funcionalidad ISR

### ISSUE THREAD

**Issue by srodriguezp** [IIC2343/Syllabus-2023-1#160]
Luego de acceder a los registros de estados y generar los comandos correspondientes ¿La ISR debe enviar la señal EOI al controlador o no es necesario?

**Comment by tocococa** [comment]
Hola @srodriguezp, en RISC-V no existe la instrucción EOI, al terminar una ISR sales con `mret/uret/sretdependiendo del modo de operación.
