### ISSUE TITLE
[T3 - P2.b] Escribir el resultado de la operación al inicio de la cinta magnética

### ISSUE THREAD

**Issue by JosefaPaz** [IIC2343/Syllabus-2023-1#161]
Hola! 

Tenía una duda respecto al ítem "3. Escribir el resultado de la operación al inicio de la cinta magnética." Esto significaría que si por ejemplo tengo el carácter ASCII "H", debo escribir primero "H" y luego debe seguirle todo lo que ya está en la cinta magnética, o debo sobreescribir el carácter que ya está en la posición 0 y cambiarlo por "H"?

Gracias :)

**Comment by tocococa** [comment]
Hola @JosefaPaz, basta con que sobrescribas el carácter que corresponda.
