### ISSUE TITLE
[T3 - P2.b] Tiempo de ejecucion, que tipo de dato escribir en la cinta y duda numero random

### ISSUE THREAD

**Issue by oscars810** [IIC2343/Syllabus-2023-1#162]
Hola! tengo 3 dudas:

1)
En la ultima interaccion se nos pide `Escribir los últimos tres caracteres de la cinta magnética en la impresora.` pero para esto es necesario movernos hasta casi el final de la cinta lo que toma bastante tiempo por como está definido el `seek_delay` ya que el largo de la cinta es 1767.

``` python
def __read(self) -> str:
          pointer = self.next_head
          def seek_delay(head: int, pointer: int) -> None:
              time.sleep(abs(head - pointer) / 10)
```

Entonces quería saber si esto se tiene en consideracion para la correccion y que no se piense que el programa quedó pegado, o si podemos subir el codigo con un `time.sleep(1)` para agilizar la ejecución.

2)
Mi segunda duda es como escribir el resultado, por ejemplo si me da `3123`solo debo ir a la posicion 0 y pasarle ese numero al out para que lo escriba? o deberiamos de transformarlo a string o ASCII

3) 
Por ultimo, el numero que obtengo con entropy es siempre el mismo, noté que tiene puesta una seed pero quería saber tambien si es normal que sea siempre el mismo.

**Comment by scagender** [comment]
son los ultimos 3? o pueden ser de cualquier posición?

**Comment by tocococa** [comment]
Hola @oscars810 @scagender, puedes modificar como te parezca el seek delay si no quieres esperar tanto tiempo. Para escribir puedes transformarlo a ASCII o no, queda a tu criterio. Es normal que el numero sea el mismo.
