### ISSUE TITLE
[T3 - P2.b] Preguntas de enunciado

### ISSUE THREAD

**Issue by josefinacortes** [IIC2343/Syllabus-2023-1#163]
Hola!
Tengo algunas preguntas del enunciado. Primero, cuando nos dicen "Leer un par de números de la cinta magnética a partir de una posición data obtenida del dispositivo entropy". Entiendo que él data de entropy es un número fijo, por lo que no entiendo como "leer un par de números". Además, la cinta magnética me da un string, de otras issues he visto que hay que usar ASCII para manejarlo, pero no me queda muy claro. Lo que más me complica es de donde sacar esos "dos números" que nos piden, cuando entropy solo nos da desde donde debemos partir, o lo estoy entendiendo mal?
Muchas gracias

**Comment by tocococa** [comment]
Hola @josefinacortes, puedes sumarle un offset al valor que te entrega entropy si quieres tener números diferentes. Para tomar dos números basta que leas la posición que te da entropy, leas 2 bytes, los interpretes como int según su valor ASCII y trabajes con eso.

**Comment by josefinacortes** [comment]
Muchas gracias, y ese offset lo elijo yo? Gracias!

**Comment by tocococa** [comment]
Sip.
