### ISSUE TITLE
[T3 - P2.a] Elemento dir_ise

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2343/Syllabus-2023-1#164]
Holaa,
Estaba tratando de entender bien la pregunta 2a, sin embargo no comprendo bien a que se refiere el elemento `dir_ise`, no me queda claro cual es la función, ya que la de los otros elementos estoy claro, sin embargo la de este no se muy bien lo que indica, además que no se relaciona con nada dentro de la tabla de especificaciones de estados y comandos.

<img width="730" alt="Screenshot 2023-05-31 at 23 45 06" src="https://github.com/IIC2343/Syllabus-2023-1/assets/62019329/ffad34dd-5fbc-4c9b-9db7-5d6dea9a13c2">

**Comment by Geeermy** [comment]
¡Hola!

Es un dato que no necesitan utilizar, pero que es necesario definir en un sistema "real": la CPU que hace el llamado a la subrutina debe, en primer lugar, leer el contenido de esa dirección para poder hacer el llamado a la ISR de forma correcta a través de esta dirección de memoria (que apunta a las instrucciones del programa que les pedimos a ustedes que programen en esta pregunta).

En resumen: es algo teórico que no necesitan utilizar, pero que se debe definir al momento de documentar el uso y direcciones de dispositivos I/O.

¡Saludos!
