### ISSUE TITLE
[T3 - P2] Probar código

### ISSUE THREAD

**Issue by NicoJGutierrez** [IIC2343/Syllabus-2023-1#168]
Tanto en la 2a como en la 2b no sé cómo probar el código que hice.
En la 2a porque el script que uso yo podría ser muy distinto al que usen ustedes y no sé cómo adaptarme al uso que le den ustedes.
En la 2b porque el módulo me tira el error de que le falta un archivo "pmio.logs".
Gracias de antemano!!!

**Comment by Geeermy** [comment]
¡Hola Nico!

Respecto a la 2.a. no te preocupes. Si la forma en la que probaste funciona efectivamente con las direcciones de memoria que debería (según enunciado), entonces estarás bien. No vamos a usar un "script" para probarlo, haremos más que todo una revisión de código.

Respecto a la 2.b., la solución rápida sería crear el archivo `pmio.logs` dentro de una carpeta `logs` en el mismo repositorio donde está tu código (pensaría que se crea automáticamente, pero sería la forma segura de que no se te caiga por eso).

¡Saludos!
