### ISSUE TITLE
[t3 - p2.b]

### ISSUE THREAD

**Issue by francoschiaffino** [IIC2343/Syllabus-2023-1#169]
Hola! Cuando dice que hay que realizar 3 operaciones de los valores ASCII obtenidos de entropy, es que hay que realizar cada operación sobre los valores iniciales o ir aplicandole la operación al resultado de cada una que se guarda en el registro A. Por ejemplo, si tengo los valores 2 y 3, sería
2*3 = 6
2+3 = 5
2-3 = -1

ó

2*3 = 6
6+3 = 9
9-3= 6

**Comment by Geeermy** [comment]
¡Hola!

En línea con lo discutido en #155, queda a criterio tuyo (coméntalo en el código o en el PDF si incluyes uno), pero ojalá hagas lo que te sea más fácil según cómo funciona el coprocesador. :)

¡Saludos!

**Comment by francoschiaffino** [comment]
Ok, gracias!
