### ISSUE TITLE
[T3-P2.A] Uso de stack

### ISSUE THREAD

**Issue by tzehnder** [IIC2343/Syllabus-2023-1#170]
Hola! tengo una duda con respecto a el uso del stack en la pregunta 2.a, debemos manejar que las variables se guarden correctamente en el stack previo a la subrutina? 
si ese es el caso, cuales variables debiesen guardarse y cuales no, tengo entendido que las t son temporary y las s son saved, en ese caso debiesemos guardar las save en el stack y hacer manualmente el pop al final de nuestro script?

**Comment by Geeermy** [comment]
¡Hola!

Al igual que en los ítems de la pregunta 1, debes respaldar los valores en el _stack_ según la convención de llamada a partir de los registros que uses, siguiendo los siguientes puntos:

1. Los registros que debes respaldar son solo los que uses en el código, no todos.
2. Los registros de tipo `s` deben ser respaldados **por la subrutina llamada** (_callee_), ya que se le debe asegurar al _caller_ que su valor no cambiará después de la ejecución de la subrutina. Entonces, los guardas en el _stack_  **dentro** de la subrutina (y los restauras antes del `ret`).
3. Los registros de tipo `t` deben ser respaldados **por quién llama a la subrutina** (_caller_), ya que estos son temporales y pueden cambiar su valor dentro de ella sin problemas. Entonces, los guardas **antes** del `call` en el _stack_ y los restauras después de este.

En los archivos de las ayudantías de RISC-V puedes ver algunos ejemplos de esto. :)

¡Saludos!

**Comment by tzehnder** [comment]
Muchas gracias! me sirvieron tus recomendaciones, sigo con un par de dudas. 
La idea de los valores s, es que estoy pasandole argumentos a la funcion para que los ocupe, pero que al volver con el ret no hayan cambiado esos valores o no? 
Cuando me dicen que se encargara de activar apagar el freno de emergencia simplemente debo poner 127 en ese registro o no? 
De la mano con eso, si para notificar la locomotora el valor de reg_tr debe ser 255, simplemente debo escribir en su direccion ese valor y se notificara?

**Comment by Geeermy** [comment]
1. Usar los registros `s` como argumentos para una subrutina está mal según la convención. Por estándar utilizas los registros `a`. Si usas los registros `s` dentro de la subrutina se asume que no cambian (por ejemplo, constantes y cosas de ese estilo), pero no deberías usarlos como argumentos de una subrutina.
2. Sí, solo escribir en ese registro ese valor.
3. Sí, puedes asumir que al escribir ese valor se notificará (discutido en #157 como referencia)
4. Si te refieres a "valores de retorno", por estándar los registros `a0` y `a1` guardan los valores de retorno de una función. Deberías usar esos y, posterior al llamado, asumir que en ellos tienes dichos valores.

¡Saludos!

**Comment by IgnAMS** [comment]
Hola profesor, estuve viendo ayudantias y en el ejercicio `subrutinas.asm` se usan los registros `s`, pero estos se guardan en el stack, no eso es la manera correcta de manejarlos?

**Comment by Geeermy** [comment]
@IgnAMS ¡Hola Nano! Al final depende del tipo de registro que utilices. En ese ejemplo, se preservan **dentro** de la subrutina. Los registros `s` son del tipo _callee saved_ y, por ello, la subrutina llamada debe resguardar su valor dentro del _stack_ y recuperarlos al final de la llamada (antes de retornar). Si se hubieran utilizado los registros `t` en vez de los `s`, estos se habrían resguardado antes del call y se habrían recuperado después del mismo al ser _caller saved_ (quien llama la subrutina se encarga de resguardarlos).

¡Espero se entienda!
