### ISSUE TITLE
T3 - P1.b

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2343/Syllabus-2023-1#171]
Hola!

Cuando dicen cualquier N de input se refieren que tenemos que aceptar un input de consola? O que ustedes manualmente editan el codigo y cambian el N: .word X  , cambiando el X? 

Se puede hacer esto aceptando un input de consola que reciba un número y no ocupar la label N del todo?

**Comment by Geeermy** [comment]
¡Hola!

Nos referimos a lo segundo: modificaremos manualmente el valor.

En teoría podrías leer de consola con [el ecall 5 "ReadInt"](https://github.com/TheThirdOne/rars/wiki/Environment-Calls), pero no es lo que buscamos evaluar.

¡Saludos!

**Comment by sebaelsaca** [comment]
Gracias @Geeermy . Lo hice de la segunda forma, eso se penalizaría o se puedde para dejarlo así?

**Comment by Geeermy** [comment]
Puedes dejarlo así, pero déjalo comentado en el script al principip, por fis!
