### ISSUE TITLE
[T3-P2.A] Duda con estados no deseados

### ISSUE THREAD

**Issue by piacabrera** [IIC2343/Syllabus-2023-1#173]
Hola! me queda una duda con que es un estado no deseado, "derrame; temperatura distinta a la normal; existencia de elementos sobresalientes"

Por ejemplo, con temperatura distinta a la normal se refiere a el sensor distinto de 127, o por otro lado el sensor igual a 255 o igual a 1? O es equivalente escoger cualquiera de estas alternativas. 
y mi otra pregunta es, es posible que el sensor tome un valor distinto a los de la tabla? 

Muchas gracias :)

**Comment by Geeermy** [comment]
¡Hola!

1. Cualquier valor que sea distinto de 127.
2. Puedes asumir que solo toma los valores de la tabla.

¡Saludos! :)
