### ISSUE TITLE
T3 -P2.a

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2343/Syllabus-2023-1#174]
Es necesario llamar "jal" o podemos asumir que esto lo llaman ustedes haciendo que nosotros solo manejemos mret? Porque actualmente solo termino con mret como piden, pero no manejo un comando de subrutina al inicio.

**Comment by Geeermy** [comment]
¡Hola!

No es necesario. Puedes asumir que la subrutina que defines después nosotros la podemos llamar (por ejemplo, usando la dirección de la ISR descrita en el enunciado). Recordar que este ejercicio es más bien "teórico" porque no se puede probar en RARS ni tendremos su ISR ubicada en la porción de memoria que corresponde.

¡Saludos!
