### ISSUE TITLE
[T2 P2.a]

### ISSUE THREAD

**Issue by francoschiaffino** [IIC2343/Syllabus-2023-1#175]
Hola! En una issue que ya se me perdió, decían que si usabas registros temporales en tu subrutina, tenias que respaldarlos, pero en la ayudantía dice que los registros t0-t2 no necesitan ser respaldados, ya que son registros temporales.

![image](https://github.com/IIC2343/Syllabus-2023-1/assets/69703636/a5e64b05-6085-465b-a550-dc679b337f16)
![image](https://github.com/IIC2343/Syllabus-2023-1/assets/69703636/f436d25f-1af6-4025-a9a5-aa461e5dbca8)

Teniendo esto en cuenta, si solo uso los registros t0 -t2 en mi subrutina, no tengo que respaldar absolutamente nada?

**Comment by Geeermy** [comment]
¡Hola!

Como no se preservan entre llamadas, son _caller saved_, esto quiere decir que **quien llama a la subrutina** está a cargo de respaldar los valores de los registros (es decir, los guardas en el _stack_ antes del `call` y los recuperas posterior al `call`).

Ahora, si fuera de tu subrutina no haces uso de ellos (asumo que es el caso dado que preguntas en el contexto de la ISR), entonces no, no tendrías que preocuparte del respaldo (se asume que quien llame a la ISR los respaldará).

¡Saludos!
