### ISSUE TITLE
[T3-P2.b] duda resultado

### ISSUE THREAD

**Issue by martin-santiago** [IIC2343/Syllabus-2023-1#176]
Hola, en la 2b en el punto 3, nos piden usar el resultado de la punto 2, debemos usar cualquier resultado (suma, resta, multiplicacion, division)? O hay que usar uno en especifico?

Y otra duda, hay que escribir el valor en ascii en la cinta magnética o escribir el valor como caracter, muchas gracias!

**Comment by tocococa** [comment]
Hola @martin-santiago, da un poco lo mismo el resultado, porque si aplicaste las operaciones consecutivamente al resultado anterior tendrías solo un resultado. 

El valor lo deberías escribir como su carácter ASCII. Si te queda un valor muy grande puedes usar %.

**Comment by diegocostares** [comment]
@tocococa no me queda muy claro, como lo puedo imprimir como ASCII?
