### ISSUE TITLE
[T3-p1.d]: Dudas sobre listas

### ISSUE THREAD

**Issue by diegocostares** [IIC2343/Syllabus-2023-1#177]
Hola, estoy super complicado haciendo este código y quería preguntar dos cosas:
1. Si entrego un algoritmo que resuelva el problema en python y algo del codigo en rISC-V cuanto puntaje podria llegar a conseguir?
2. Como puedo crear una lista de tamaño N de puros False (0)?
3. Como podria hacer algo como un `list.apped(i)` p un `list[i]` en rISC-V?
4. Podrian darme un ejemplo de una sub rutina que se le incluyan saltos como parametros? O no es posible hacer esto?
Generalizándolo al máximo, quería hacer algo como esto (claramente no funciona y no termina XD):
```asm
la a0, direccion_de_salto1
la a1, direccion_de_salto2
jal ra, sub_rutina

sub_rutina:
    loop1:
        beq t1, t2, a0
        loop1
```

**Comment by frvalenzuela** [comment]
Hola @diegocostares !

1. No se dará puntaje por códigos escritos en otros lenguajes
2. Las listas son objetos de alto nivel de `python`, lo más cercano son arreglos, que se definen como se muestra en los códigos base de la pregunta.
3. No, por lo descrito en 1
4.  Recomiendo revisar el ejemplo de factorial de la siguiente [clase ](https://cursos.canvas.uc.cl/courses/53215/files/7921765?module_item_id=1611636)

Saludos!
