### ISSUE TITLE
[T3-P1.C] Uso de etiqueta out

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2343/Syllabus-2023-1#180]
Hola,
En la P1.C, la idea es que out corresponda a un arreglo? O puedo ir haciendo "print" a medida que voy obteniendo los resultados?
Esto lo pregunto porque no me queda claro que es lo que esperan que hagamos con la etiqueta `.out`

**Comment by tocococa** [comment]
Hola @Mamunoz42, si dejas tu resultado en un arreglo a partir de la etiqueta `.out` el resultado se puede ver en el visualizador de la sección data del emulador, o puedes usar una ecall para imprimirlo, como prefieras.
