### ISSUE TITLE
[T3-P1.b] Duda convencion de llamada

### ISSUE THREAD

**Issue by martin-santiago** [IIC2343/Syllabus-2023-1#181]
Hola!

Tengo una duda, si en una subrutina devuelvo más de dos argumentos, puedo usar los registros mayores a a0 y a1 que son los que usa la convencion? Que tan grave es usar usar del a2-a7 para los valores de retorno

**Comment by rosariodominguezm** [comment]
Hola!

Qué diferencia hay entre usar jal label + jr ra o call + ret. Entiendo que los dos sirven para llamar funciones. Se puede usar cualquiera para la tarea?

**Comment by Geeermy** [comment]
¡Hola!

La diferencia es que call y ret son "pseudo-instrucciones": en la práctica realizan la misma ejecución solo que conviene hacer uso de estas últimas para hacer el código más legible. En la tarea puedes usar cualquiera. :)

¡Saludos!
