### ISSUE TITLE
Enunciados Tarea

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2343/Syllabus-2023-1#182]
Muy buenas tardes 😄 

Hago esta issue para dar a conocer mi punto de vista respecto a como se están evaluando las tareas en el ramo y hacer una solicitud para la tarea 4.

Podrían ser mas claros en el enunciado de la tarea 4 respecto a los elementos que se evalúan? Me pasa que en las pautas evalúan cosas y descuentas puntos por elementos que no son mencionados claramente en el enunciado.
Un ejemplo claro es en la Tarea 2, en donde hay ítems en los que se descuenta por no agregar señales, sin embargo en ninguna parte se mencionaba que era importante agregar las señales.

Siento que consideran como obvias cosas que no deberían serlo, y nosotros como alumnos deberíamos tener claridad respecto a que buscan evaluar en las tareas desarrolladas.

Por otra parte, considero que no es posible que las tareas tengan más de una versión, y que no se anuncien cambios que terminan afectando en lo que se pudo haber desarrollado antes de que se hicieran los cambios de enunciado.

Muchas gracias

**Comment by Geeermy** [comment]
¡Hola Manuel! Espero que estés bien. :)

Hablé de esto en la clase de hoy pero lamentablemente no te vi. De todas formas me parece importante dar una respuesta oficial a tu comentario. Quise conversar con el equipo docente antes para no responder de forma apresurada, lo siento si se sintió como si fueras ignorado, créeme que no fue el caso.

Respecto a tus comentarios, responderé en puntos separados:

- Existen casos en los que estoy de acuerdo que debemos ser más explícitos y, en línea con lo solicitado, el enunciado de la Tarea 4 es súper transparente respecto a la asignación de puntaje, así que espero que en ese sentido puedan estar más tranquilos con lo que se evaluará. Ahora, llega un punto en el que no podemos entregar la especificación completa sin caer en darles la respuesta esperada, así como también hay otros elementos que **sí esperamos** que consideren en una pregunta, esté explicitado o no. Por ejemplo, si les pedimos que realicen una modificación sobre una microarquitectura y no realizan una conexión o no agregan una señal, su implementación **no funcionará** y no podemos darles el puntaje completo por lo mismo. En el proyecto mismo han podido dar cuenta de cómo cosas "chicas" como esa inciden de manera significativa en la ejecución de instrucciones en una microarquitectura. Desde esa perspectiva, como cuerpo docente necesitamos que ustedes demuestren que manejan los objetivos de aprendizaje mínimos esperados en las evaluaciones incluyendo cosas esenciales como dichas señales.
- Sin perjuicio de lo anterior, me consta que en la Tarea 2 hay casos en los que hubo descuentos de puntaje injustificados en desarrollos que contenían lo suficiente para considerarse correctos. Además, en otros casos la retroalimentación entregada no fue lo suficientemente clara para que pudieran entender bien los descuentos que se les hizo. Estamos trabajando como equipo en medidas correctivas para estos casos, apenas lo tengamos definido les enviaré un anuncio al respecto.
- Por último, respecto a las modificaciones de enunciados de tareas: Existen situaciones en los que nos vemos en la obligación de modificar enunciados de tareas por errores que inciden directamente en sus respuestas (como fue el caso de la tarea 1 y 2), por lo que es difícil que nos solicites no modificar enunciados si es que hay errores que claramente los pueden perjudicar. Ahora, si bien en la tarea 3 la modificación que se realizó sobre la pregunta 2.B. se hizo para reducir la ambigüedad y que pudieran contestarla más seguros, es cierto que debimos haberlo enunciado con anticipación y nos disculpamos por no haberlo hecho. En este caso, la pauta será flexible para que nadie se vea perjudicado por su respuesta si es que la hizo basándose en la versión anterior del enunciado.

Espero que con todo lo anterior puedan estar más tranquilos con lo que nos queda de semestre. Quiero además añadir que siempre estamos abiertos a escucharlos y a ayudarlos si es que nos necesitan. Tienen todos nuestros correos, canvas y este mismo medio para hacerlo. :)

¡Un abrazo!
