### ISSUE TITLE
 [Proyecto] Uso de los componentes de input

### ISSUE THREAD

**Issue by jrvalenzuela** [IIC2343/Syllabus-2023-1#183]
En el enunciado, donde se listan los aspectos mínimos del juego que hay que hacer, el punto 7 dice `Hacer uso creativo de los componentes de input (botones, siwtches, Timer) y output (LEDs, Displays, LCD)`. Esto no significa que tenemos que necesariamente utilizar todos los componentes en nuestro juego, o si?

**Comment by drcid98** [comment]
Hola! No es necesario usar todos los input/output para tu juego.
