### ISSUE TITLE
[T4 -  P1] Dudas generales

### ISSUE THREAD

**Issue by Dafnemami** [IIC2343/Syllabus-2023-1#184]
Holis!,

1. Se espera que implementemos los 3 casos de configuraciones de memoria y luego se nos evaluarán dos al azar?

2. Me confunden estos 3 puntos al final:
- Todas las direcciones de la secuencia son válidas para la configuración de memoria entregada.
- El formato del archivo de input siempre será válido.
- No se utilizarán rutas de archivos que no existan para probar su tarea 

Se refiere a que no nos evaluarán con nada ¨raro¨? Sobre el último punto, pregunto más por curiosidad, por qué podrían evaluar con rutas de archivos que no existan? como que no entiendo por qué fue necesario aclarar eso.

Saludos!

**Comment by Geeermy** [comment]
¡Hola Dafne! Respondo punto a punto:

1. No, usaremos dos configuraciones de memoria (_i.e._ combinaciones de memoria principal-caché de tamaños distintos-secuencia de direcciones) para cada función de correspondencia. Como tenemos 2 combinaciones de memoria y 3 funciones de correspondencia, tienes 2 * 3 = 6 combinaciones distintas de _input_, por eso en el enunciado se dice que se harán 6 _tests_.
2. Sí, básicamente queremos enfatizar en que no probaremos ningún caso raro o extraño, simplemente queremos que focalicen el desarrollo en los contenidos de memoria caché. Lo de las rutas de archivo es por si alguien quería ir "más allá" y arrojar alguna excepción si es que la ruta de archivo entregada no existiera, como para asegurarnos que no inviertan tiempo en eso. 😅  Quizás era un poco excesivo señalarlo pero nunca está de más.

¡Un abrazo!

PD: Editaré tu _issue_ indicando que esta es la T4 y no la T3.
