### ISSUE TITLE
[E2-E3] ERROR libreria IIC2343

### ISSUE THREAD

**Issue by alvarocisternas** [IIC2343/Syllabus-2023-1#185]
Hola, estamos teniendo problemas al correr el python conectado a vivado mediante la libreria iic2343. La libreria constantemente arroja que no esta instalada en el computador, ya hemos probado en 3 computadores y en los tres nos arroja exactamente lo mismo.

![image](https://github.com/IIC2343/Syllabus-2023-1/assets/80793627/df15a01c-c632-4561-a730-43ef0d909136)

Existe alguna posibilidad de acceder al repositorio de la libreria para probarlo de manera local?

**Comment by frvalenzuela** [comment]
Hola @alvarocisternas !

Trataron ejecutarlo desde el idle de python ? Y también recomiendo tratar usando `pip3 install` como también revisar si tienen más de una versión de python, e instalarla en dicha versión. Por el momento no se encuentra de manera local, solo tenemos la alternativa antes mencionada.

Quedo atento a sus comentarios.

Saludos!
