### ISSUE TITLE
[T4 - P1]  Fully Associative y Caché llena

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2343/Syllabus-2023-1#188]
Hola, 
tenía una duda al respecto de la función de correspondencia _Fully Associative_. Cuando la caché se llena y se hace un llamado a una dirección que no está en la caché: ¿el criterio por el cual esta se va a continuar llenando queda a nuestra elección? 
Pregunto lo anterior porque al implementar un programa que utiliza dicha función de correspondencia he obtenido el siguiente _output_:

0M 1H 5M 7M 10M 13M 4H 6H
HR=0.375
ÍNDICE LÍNEA | TAG | BIT VALIDEZ
00 | 000 | 1
01 | 101 | 1
10 | 010 | 1
11 | 011 | 1

Que es similar al que se muestra en el enunciado para el mismo test, sin embargo, difieren en la tabla final que se presenta.

**Comment by Geeermy** [comment]
¡Hola!

No, no queda a criterio de ustedes. En el enunciado se indica que la política de reemplazo es LRU (_Least Recently Used_). Bajo este criterio tienes que reemplazar la línea de caché que se haya accedido hace más tiempo. Entonces, debes encontrar la forma de ir guardando esa información para cada línea de la caché por cada acceso de memoria de forma que puedas tomar la decisión correcta bajo esta política. En las diapositivas de este contenido de la sección 2 puedes ver el mismo ejemplo del enunciado para ver cómo se escogen las líneas a reemplazar para llegar al resultado esperado.

La forma de guardar el tiempo de acceso sí queda a criterio de ustedes, como les sea más fácil. :)

¡Saludos!
