### ISSUE TITLE
[T4 - P1]: duda sobre cantidad de bits

### ISSUE THREAD

**Issue by martin-iturralde** [IIC2343/Syllabus-2023-1#189]
Hola! Tengo una duda sobre como aproximar una división de bytes a bits. Por ejemplo, si tengo 20MB/6KB = 3413.333KB. Si es que calculo cuanto es 2 elevado a X, X sería 11.7, aproximadamente. En este caso, 11.7 serían los bits. Entonces, mi pregunta es: en este tipo de aproximaciones, siempre se redondeada hacia arriba o hacia abajo? O, depende si es mayor o menor a .5?
Gracias de antemano!

**Comment by Geeermy** [comment]
¡Hola!

En ese tipo de caso siempre debes redondear **hacia arriba**. Tienes que pensar que esos bits te dan la cantidad que necesitas para **direccionar una palabra dentro de un bloque de memoria o línea de la caché**. Si utilizas 11 bits, habrá palabras que no alcanzarás a direccionar. Si utilizar 12 bits te sobrarán, pero no habrá palabra dentro del bloque/línea que no puedas direccionar. Por eso es mejor redondear.

Ahora: este es un detalle que modificaré del enunciado y que avisaré vía canvas, pero todos los valores de tamaños serán **potencias de 2**, así que en ningún caso tendrás un exponente con parte decimal, puedes despreocuparte de eso. :)

¡Saludos!
