### ISSUE TITLE
Duda P1 - T4

### ISSUE THREAD

**Issue by alvarocisternas** [IIC2343/Syllabus-2023-1#190]
Hola!
Tengo la siguiente duda con respecto al input y output de la P1:
En la diapositiva 52 de la clase 11 del profesor Germán se señala "Caché de 8 bytes y 4 líneas", por lo que en la diapositiva 54 se puede visualizar que al existir **4 líneas**, el índice de línea se enumera del 0 al 3 (00, 01, 01, 11).

En el ejemplo del input de la tarea existen **2 líneas**, y los índices de línea también se enumeran del 0 al 3 en el output (00, 01, 01, 11).

¿Para que el output de la tarea estuviese correcto debiesen ser 4 líneas en el input?

**Comment by Geeermy** [comment]
¡Hola!

El _input_ coincide con el ejemplo del profesor Germán (yo, jeje). Interpretaste mal el formato del _input_: `LINE_SIZE` no indica la cantidad de líneas, sino que indica el tamaño **en bytes** de una línea. Entonces: `# Líneas = CACHE_SIZE / LINE_SIZE`. Si aplicas esto al ejemplo del enunciado, tendrás `# Líneas = 8 / 2 = 4`.

Además, puedes asumir que esta división siempre te dará un número entero (y potencia de 2, además).

¡Saludos! :)

**Comment by alvarocisternas** [comment]
Muchas gracias, me quedó claro!

Saludos
