### ISSUE TITLE
[T4 - P1] Tests

### ISSUE THREAD

**Issue by sperezmasri** [IIC2343/Syllabus-2023-1#192]
Hola! Quería saber si podían subir más tests de ejemplo con el output esperado para poder chequear si mi programa está realmente bien implementado. Gracias de antemano, saludos :smile:

**Comment by Geeermy** [comment]
¡Hola!

Trataremos de subir una configuración de memoria más grande y con un ejemplo de secuencia para que prueben con las 3 funciones de correspondencia. Ahora, la idea es que también ustedes puedan elaborar sus propios _tests_ para verificar si su programa está realmente correcto. Parte de lo esperado es que sepan cómo se va actualizando una caché según una secuencia de accesos a memoria y es algo que se evalúa en el curso (incluido el examen). Lo comento para que puedas empezar a revisar por tu cuenta desde ya para buscar posibles errores de implementación. 🙏 

Les enviaré un aviso para cuando esta segunda tanda de _tests_ esté subida. :)

¡Un abrazo!

**Comment by sperezmasri** [comment]
Ok, muchas gracias!

**Comment by josefapv** [comment]
Hola! Quería saber si estos tests estarán pronto?

**Comment by Geeermy** [comment]
@josefapv @sperezmasri ¡Subidos! 😄
