### ISSUE TITLE
[T4 P1]

### ISSUE THREAD

**Issue by francoschiaffino** [IIC2343/Syllabus-2023-1#193]
Hola! En el ejemplo del enunciado, el acceso a 4 no debería ser un miss? ya que, si bien se guarda el 4 y el 5 en la caché en el tercer acceso, luego este bloque se reemplaza con los bloques 12 y 13, al acceder a 13, justo antes del acceso a 4

![image](https://github.com/IIC2343/Syllabus-2023-1/assets/69703636/70087e28-a3bf-4f08-bd95-909f3817c3fc)

**Comment by Geeermy** [comment]
¡Hola!

No, eso ocurre con la función de correspondencia _directly mapped_, donde se realiza el reemplazo porque ambos bloques se mapean a la misma línea. En 2-_way associate_, por política de reemplazo LRU escoges la línea accedida **hace más tiempo** dentro del conjunto al que se mapea el bloque. En este caso: `13_{10} = 1101_{2}`, donde la dirección se desagrega así: `11|0|1`, siendo la primera porción el _tag_, la segunda el conjunto y la tercera el _offset_. Antes de realizar el acceso, este es el estado de la caché:

<img width="1255" alt="Captura de Pantalla 2023-06-16 a la(s) 18 25 26" src="https://github.com/IIC2343/Syllabus-2023-1/assets/5559611/99a0ffc1-44da-4880-9d4d-03eb1ca8d16e">

Luego de que accedes a la dirección 13, escoges la línea dentro del conjunto 0 accedida hace más tiempo (que sería la línea 00):

<img width="1252" alt="Captura de Pantalla 2023-06-16 a la(s) 18 25 34" src="https://github.com/IIC2343/Syllabus-2023-1/assets/5559611/6eddd263-1433-45c4-812a-2e16dcd1f417">

Finalmente, al acceder a la dirección 4, como en el acceso anterior **no se reemplazó su línea**, entonces tendrás un _hit_ (y al mismo tiempo actualizarás los tiempos de acceso).

Por si no los has visto, estos ejemplos están en la clase 11 de la sección 2 (diapositiva 51 en adelante). Son los mismos ejemplos que el enunciado.

¡Saludos!

**Comment by francoschiaffino** [comment]
cierto, leí mal, pensé que era directly mapped jajajaja. Muchas gracias!

**Comment by berrazuriz3** [comment]
Hola, a mí me surgió la duda en el output de DM

![image](https://github.com/IIC2343/Syllabus-2023-1/assets/101363118/8ac040c4-7d93-4809-be67-e6e86e97ca69)

En este caso, 6 no debiese ser un miss, ya que se hizo acceso a 4 (0100, 01 el indice y 0 el tag) y después se hace acceso a 6 (0110, 01 indice y 1 el tag). No estoy seguro si estoy bien, pero ya que el acceso a 4 fue un miss, se guarda en el indice 01 el tag 0, y cuando se intenta acceder a 6, es un miss ya que tiene el mismo indice y distinto tag?

**Comment by Geeermy** [comment]
@berrazuriz3 ¡Hola!

Es que lo estás viendo al revés. El orden en el que se ve la dirección es:

4 = 0(_tag_)|10(índice de línea)|0(_offset_)
6 = 0(_tag_)|11(índice de línea)|0(_offset_)

Entonces, como se mapean a líneas distintas, no se reemplazan entre sí. Importante destacar que, en cualquier función de correspondencia, **la porción de bits más significativa siempre será utilizada para el _tag_** (variando solo la cantidad de bits según la configuración de las memorias y la función de correspondencia).

El ejemplo de _Directly Mapped_ está en la clase 11 de la sección 2 (diapositivas 53-62) y la explicación de los bits de _tag_ en las diapositivas 38-41.

¡Espero que se entienda!
