### ISSUE TITLE
[Proyecto] Duda: Juego de enunciado y condición de switch de inicio para volver a jugar

### ISSUE THREAD

**Issue by nvaldiviesoo** [IIC2343/Syllabus-2023-1#195]
¡Hola!

En el contexto de la entrega 3 del proyecto, me surge una pregunta respecto al juego que hay que implementar. 
Un punto del enunciado menciona lo siguiente:

<img width="650" alt="Captura de pantalla 2023-06-17 a la(s) 17 46 45" src="https://github.com/IIC2343/Syllabus-2023-1/assets/69522408/30fdd496-2e80-41e5-b8c8-54f344ea07a1">

No comprendo si al volver el switch de inicio original: 

**A)** Empieza automáticamente la cuenta regresiva para volver a jugar
o
**B)** El juego vuelva a quedar en período de espera, en el cual si un jugador aprieta un botón se debe mostrar su número en el
Display (haciendo que el switch deba cambiar de posición una vez más para que empiece la cuenta regresiva)
?

Gracias de antemano

**Comment by frvalenzuela** [comment]
Opción B 

Porque según las reglas del juego, el switch de inicia es que parte la cuenta regresiva

Una vez iniciado se debe hacer la cuenta regresiva.

Y el juego iniciado está definido por levantar el switch de inicio (según las reglas de enunciado).
Saludos !
