### ISSUE TITLE
[T4-P2] Duda último inciso

### ISSUE THREAD

**Issue by HAWK-EF2021** [IIC2343/Syllabus-2023-1#196]
Hola, me gustaría saber si en el último inciso debemos considerar los bits de metadata que se ocupan en el tercer inciso para los bits de la TLB.

**Comment by Geeermy** [comment]
¡Hola!

Por construcción, los marcos físicos que se guardan en TLB son válidos y no requieren de _swapping_, por lo que los bits de _metadata_ del tercer inciso no se guardan al almacenar la información de la traducción en esta caché. No obstante, y sin profundizar para no dar la respuesta textual, recuerda que **es una memoria caché**.

¡Saludos!

**Comment by HAWK-EF2021** [comment]
Perfecto gracias!
