### ISSUE TITLE
[T4 - P1] cantidad de bits de número mayor a bits de dirección

### ISSUE THREAD

**Issue by nicogrecod18** [IIC2343/Syllabus-2023-1#199]
Hola,

Quería preguntar si es posible que pase por ejemplo que nos entreguen que el tamaño de la caché sea 8 -> por lo tanto tenemos 4 bits de dirección, y que en la secuencia de direcciones nos salga un número que sea representado por más de 4 bits, como por ejemplo 36 -> 100100, el cual es representado por 6 bits.  En caso de que sea posible casos asi, ¿que debiesemos hacer ? 

De antemano, gracias

**Comment by Geeermy** [comment]
¡Hola!

Primero: los bits de dirección dependen de la **memoria**, no de la caché. Además, para 8 direcciones serían 3 bits, no 4.

Segundo: No. Como dice el enunciado, solo probaremos direcciones válidas. Si tienes un máximo de 8 direcciones, no te ingresaremos en la secuencia números mayores o iguales a 8 (dado que solo las direcciones 0 a 7 serían válidas en esta configuración).

¡Saludos!

**Comment by nicogrecod18** [comment]
Muchas gracias por las aclaraciones !!
