### ISSUE TITLE
[Proyecto] Puntajes 

### ISSUE THREAD

**Issue by catalinacarter** [IIC2343/Syllabus-2023-1#200]
Hola!! Tengo una duda sobre los puntajes, para esta entrega se podrá contar con puntajes intermedios en todos los tópicos? Estos son: juego de reacción, flujo creado por nosotros, informe. El enunciado me da a entender que si, pero prefiero asegurarme preguntando. O será como la entrega pasada donde hay tópicos que son todo o nada?
Gracias!!!

**Comment by frvalenzuela** [comment]
Hola!

Si, dado que no se evaluará con tests, la corrección será con puntajes parciales como la entrega 1.

Saludos!
