### ISSUE TITLE
[T4-P3] Ciclos instrucción pop

### ISSUE THREAD

**Issue by sigualt** [IIC2343/Syllabus-2023-1#201]
Hola! No tengo muy claro el concepto de ciclos en el esquema de paralelismo. Cada etapa (IF,ID, etc) se considera un ciclo o no? Es que me baja la duda al tratar de implementar la instrucción pop, debido a que piden que sean 5 ciclos para cada instrucción y que la modificación del sp se haga específicamente en wb, por lo que ahí me complico ya que habrían problemas para cumplir la condición. Quedo atento a la respuesta; muchas gracias!

**Comment by Geeermy** [comment]
¡Hola!

Sí, cada etapa es un ciclo y por ende POP debe ejecutarse en una única tanda de IF-ID-EX-MEM-WB. Ahora, este problema no es ajeno al computador básico (POP y RET con 2 ciclos), pero ya han tenido instancias donde han tenido que pensar en soluciones para eso (Tarea 2), acá tendrán que buscar soluciones para ese caso también, es parte de lo que se evaluará.

¡Saludos!

**Comment by sigualt** [comment]
Perfecto muchas gracias!
