### ISSUE TITLE
Cuenta regresiva Juego 1

### ISSUE THREAD

**Issue by scagender** [IIC2343/Syllabus-2023-1#202]
Hola, el enunciado en el juego 1 dice: "Una vez iniciado debe hacer una cuenta regresiva en el Display hasta llegar a 0". ¿Este contador debe ser exacto con los segundos? ¿Importa si el primer número que aparece en el contador tiene una duración un poco menor al resto?

**Comment by frvalenzuela** [comment]
Hola scagender!

No vamos a cronometrar que sean exactamente segundos, pero si tiene que se algo que un ayudante pueda diferenciar. Si hacen todo en microsegundos por ejemplo, no será considerado correcto. Si como dices el primer número aparece tiene una duración un poco menor al resto no será descontado puntaje.

Saludos!

**Comment by scagender** [comment]
Gracias!
