### ISSUE TITLE
[T4-P1]: Dudas con el output

### ISSUE THREAD

**Issue by mzigm** [IIC2343/Syllabus-2023-1#203]
¡Hola! ¿Cómo están? 
Tenia una duda sobre como poner el output. Tiene que imprimirse en la terminal o lo tenemos que escribir en un archivo output.txt? Gracias y Saludos!

**Comment by Geeermy** [comment]
¡Hola!

En la terminal con `print` basta, respetando los formatos de ejemplo. Después podemos pasarlos a un .txt desde la terminal si lo requerimos, pero eso lo vemos nosotros.

¡Saludos!

**Comment by mzigm** [comment]
Ya perfecto!
¡Gracias!

**Comment by mzigm** [comment]
Y el output tiene que ser idéntico al formato del ejemplo? O solo tiene que ser similar?

**Comment by Geeermy** [comment]
Te diría que lo cambies para facilitar la corrección... pero te quedó hermoso jaja. Déjalo así no más. 😊
