### ISSUE TITLE
[Proyecto] Delay time en la cuenta regresiva del juego

### ISSUE THREAD

**Issue by ignacioarteaga99** [IIC2343/Syllabus-2023-1#204]
Hola, tengo una duda respecto al juego de reacción. 
Implementé en assembly una cuenta regresiva que va mostrando los números del 5 al 0 en el display para iniciar la partida, aún no lo pruebo en la placa, pero se me viene a la cabeza que lo más seguro es que muestre los números muy rápido (o incluso pase directamente al cero), si no le agrego alguna subrutina o algo que genere un delay o un lapso de tiempo (ojalá de 1 segundo) entre el display de cada número de la cuenta regresiva.
No sé si estoy en lo correcto o no, y si es que existe alguna librería en assembly que podamos usar o alguna referencia para implementar este tiempo de delay.
Desde ya muchas gracias.

**Comment by kipasten** [comment]
Hola! 
Para la cuenta regresiva del proyecto deben poder implementarlo con input/output, que como pueden observar en el enunciado, programa 15, se hace un pseudo reloj con muy pocas instrucciones de assembly.
El timer que les entregamos para esta parte del proyecto ya entrega los segundos, con eso pueden implementar comparaciones o distintos cálculos para hacer una cuenta regresiva
