### ISSUE TITLE
[T4-P1]: Duda con resultado ejemplo DM 2

### ISSUE THREAD

**Issue by mzigm** [IIC2343/Syllabus-2023-1#205]
¡Hola! Como están?

Tengo una duda con el resultado que debería dar con el cache-input-example-dm-2.txt. En el expected output sale que el 2 tiene un HIT pero debería ser un MISS o no? Pasa lo mismo con algunos numero después.

Saludos!

**Comment by Geeermy** [comment]
¡Hola!

El _output_ es correcto. Fíjate que las líneas de la caché en dicha configuración son de **4 bytes** y no de 2. Esto significa, por ejemplo, que al tener un _miss_ copias un bloque de memoria de 4 palabras (o 4 direcciones). Al tener un _miss_ con 0, copias el bloque que posee las direcciones 0-1-2-3. Por eso vuelves a tener un _miss_ al acceder recién a la dirección 4.

Como recordatorio, los bits de _offset_ **no deben ser _hardcodeados_ a 1**, sino que dependen de la cantidad de bytes de la línea (`LINE_SIZE`). En este caso, $log_2(4) = 2$.

¡Espero que se entienda!
