### ISSUE TITLE
[T4-P2] Memoria direccionable por proceso.

### ISSUE THREAD

**Issue by robertoorrego** [IIC2343/Syllabus-2023-1#207]
Hola!
Tengo la duda sobre la máxima memoria que puede direccional cada proceso.Se refiere al total de direcciones o la cantidad de paginas que se pueden guardar en cada una?

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

Se refiere a la máxima cantidad de **bytes** que puede utilizar un proceso. Entonces, lo puedes calcular a partir de la cantidad de direcciones a la que puede acceder un proceso.

¡Un abrazo!
