### ISSUE TITLE
[T4-P3] Forwarding

### ISSUE THREAD

**Issue by a-ck** [IIC2343/Syllabus-2023-1#209]
Hola! No me queda muy claro cómo sé si quiero el dato EX/MEM.Alu o MEM/WB.Alu, no guardan lo mismo?
Desde ya gracias.

**Comment by Geeermy** [comment]
¡Hola Anto!

Es "la misma señal", pero no guardan lo mismo. MEM/WB.Alu corresponde al resultado de la instrucción que acaba de ejecutarse en la etapa MEM, mientras que EX/MEM.Alu corresponde al resultado de la instrucción que acaba de ejecutarse en la etapa EX. Entonces, haces el forwarding según la instrucción que necesites utilizar. Puntualmente, ocupas el valor MEM/WB cuando tienes un _hazard_ de datos entre la instrucción actual y la previa a la anterior:

<img width="650" alt="Captura de Pantalla 2023-06-30 a la(s) 13 58 27" src="https://github.com/IIC2343/Syllabus-2023-1/assets/5559611/14db74ee-75df-4bf3-9549-d2e4b8523618">

Aquí está el _hazard_ porque actualizas el registro A en el ciclo 5 y tú obtienes su valor en el ciclo 4.

<img width="656" alt="Captura de Pantalla 2023-06-30 a la(s) 13 58 35" src="https://github.com/IIC2343/Syllabus-2023-1/assets/5559611/12b6c25b-aefe-464e-a6ac-934e59467e6c">

Esto lo resuelves haciendo el _forwarding_ de MEM/WB.Alu hacia MuxFwA (por eso puedes ver que la flecha verde sale justamente del registro MEM/WB en el diagrama).

¡Espero se entienda! :)

**Comment by a-ck** [comment]
Por qué no guardan lo mismo? Por lo que entiendo del diagrama completo de las diapos, en la etapa MEM la señal de la ALU no sufre cambios, como que pasa de largo no más... eso es lo que no entiendo

**Comment by a-ck** [comment]
![Screenshot_20230630-141600_Drive](https://github.com/IIC2343/Syllabus-2023-1/assets/69538524/48159c97-c7b3-4c52-b2a1-607c238e333a)

**Comment by Geeermy** [comment]
@a-ck Tienes que pensar que cada instrucción está ejecutando una **instrucción distinta**.

Suponte que solo ejecutamos estas instrucciones,:

```
MOV A,2
MOV B,3
ADD A,B
```

Veamos la ejecución del pipeline, asumiendo que A y B parten en 0:

Ciclo 1: MOV A,2 (IF)
Ciclo 2: MOV B,3 (IF) | MOV A,2 (ID)
Ciclo 3: ADD A,B (IF) | MOV B,3 (ID) | MOV A,2 (EX)
Ciclo 4: ADD A,B (ID) | MOV B,3 (EX) | MOV A,2 (MEM)
Ciclo 5: ADD A,B (EX) | MOV B,3 (MEM) | MOV A,2 (WB)

En este instante tenemos el problema porque quiero hacer la suma de A y B en el ciclo 5, pero ni A ni B tienen sus valores actualizados. Entonces, a MuxFwA le transmito la señal MEM/WB.Alu porque ese es el resultado de la ALU de la instrucción MOV A,2 (que sería 2), mientras que a MuxFwB le transmito la señal EX/MEM.Alu porque es el resultado de la ALU de la instrucción MOV B,3 (que sería 3). Por eso, aunque ambos sean un output de la ALU, son outputs de instrucciones distintas.

¡Espero que ahí se entienda!

**Comment by Geeermy** [comment]
PD: Recuerda además que los registros intermedios están sincronizados por flanco de subida, por eso al iniciar el ciclo 5 MEM/WB.Alu tiene el resultado de MOV A,2 y EX/MEM.Alu tiene el resultado de MOV B,3 (y los registros que seleccionaste en ADD A,B son 0 porque no se actualizó ninguno de los dos).

**Comment by a-ck** [comment]
Yaaa perfecto ahí caché!!! Gracias :)
