### ISSUE TITLE
T4-P3 Duda con código assembly

### ISSUE THREAD

**Issue by airiquelme** [IIC2343/Syllabus-2023-1#212]
En la pregunta 3, en código de assemly se encuentra la instrucción "ADD B,1".
Esta instrucción, corresponde al del tipo de "ADD B,Lit", es decir, que se guarda en B la suma de A + Lit.
Sin embargo, este código no tiene final, pues en el registro A se encuentra el valor "2", y solo es modificado al final del código. Por lo cual "ADD B,1" perpetuamente carga "3" en B, el cual jamás será igual a 2, por lo cual el código no tiene fin.

Hice mi respuesta asumiendo que se referían a la instrucción "INC B". Esta suposición sería correcta?

**Comment by Geeermy** [comment]
¡Hola!

Se me pasó ese detalle, lo siento mucho, pero sí, la interpretación correcta es INC B (ADD B,Lit es solo la de la ISA del proyecto por si acaso, en la ISA oficial del computador básico del curso -con o sin _pipeline_ derechamente no existe).

¡Saludos!
