### ISSUE TITLE
[T1 - P3.b]

### ISSUE THREAD

**Issue by Francescorodriguezg** [IIC2343/Syllabus-2023-1#26]
Hola, no me queda claro el enunciado: "Una alternativa para bloquear el almacenamiento en un flip-flop D a partir de una
señal de control es unir esta con la señal de flancos (clock) a través de una compuerta AND.
¿Le parece esto una buena idea? Comente en base a las implicancias de esta implementación."
Mi duda es, ¿El output de esta compuerta AND donde se conecta?¿Al input D, al input del Clock o a otro lado?
Gracias de antemano!!

**Comment by Geeermy** [comment]
¡Hola!

Como se une con la señal de flancos, se refiere específicamente a conectar el resultado de la compuerta al _input_ de _clock_, como se ilustra aquí:

![IIC2343-2023-1-Duda bloqueo Latch D](https://user-images.githubusercontent.com/5559611/227798254-0bc282e0-6a4a-4d88-a47c-0b30ccdfe69e.png)

¡Saludos!

PD: Poner "T1" en vez de "Tarea1" a la próxima, por fis.

**Comment by pabloalvarez67** [comment]
Hola! no me queda claro que son los inputs de la compuerta AND, C y CLK.
