### ISSUE TITLE
[T1 - P2 .A] 

### ISSUE THREAD

**Issue by lucasilabaca** [IIC2343/Syllabus-2023-1#27]
Hola! No me queda muy claro qué se espera cuando me dicen "diseñe un comparador de números". Se espera que se muestre un diagrama del circuito? O se espera que se mencionen qué compuertas lógicas utilizar y por qué utilizarlas? O que se presente una tabla de verdad adecuada? Muchas gracias

**Comment by frvalenzuela** [comment]
Hola Lucas! 

Se espera un diagrama de circuito combinacional. 

Si algo no queda claro, no dudes en consultar. 

Saludos!
