### ISSUE TITLE
[T1 - P2.C]

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2343/Syllabus-2023-1#28]
Hola, debemos hacer un diagrama solamente de Logical Shifting? O también debemos hacerlo para un caso de Arithmetic Shift?

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

Solo logical shifting.

¡Saludos!

**Comment by pabloalvarez67** [comment]
Perfecto! y tengo otra duda.
Tenemos que diseñar un componente que contenga a estos shifts? o basta con hacer las 2 componentes por separado, y darles por ejemplo un input de X bits que defina cuántos shifts se hacen?

**Comment by pabloalvarez67** [comment]
> Perfecto! y tengo otra duda.
Tenemos que diseñar un componente que contenga a estos shifts? o basta con hacer las 2 componentes por separado, y darles por ejemplo un input de X bits que defina cuántos shifts se hacen?

**Comment by Geeermy** [comment]
Pueden ser dos componentes separadas o una única componente donde se pueda escoger la dirección del _shift_, ambas se consideran opciones válidas. :)
