### ISSUE TITLE
[T1 - P1.C]

### ISSUE THREAD

**Issue by fedezang** [IIC2343/Syllabus-2023-1#29]
Hola! Quería saber si puedo considerar que N es divisible por T .
Además, preguntar sobre el uso de un paso intermedio. ¿No se puede ocupar ningún paso intermedio? o ¿solamente no se puede ocupar la fórmula general de transformación de bases?

Gracias

**Comment by Geeermy** [comment]
¡Hola!

Si te refieres a que el resto de $N / T$ sea 0, entonces no. El algoritmo debería funcionar para $N = 3$ y $T = 2$, por ejemplo.

Respecto a tu pregunta, se refiere específicamente a la transformación a base decimal. Esto es porque no es eficiente pasar a una base "intermedia" para obtener la respuesta esperada, es lo menos óptimo. Pueden haber pasos intermedios siempre que no requieras transformar tu número a una base distinta de las que estamos utilizando ($K^N$ y $K^T$).

¡Saludos!

**Comment by Dafnemami** [comment]
@Geeermy Sobre la fórmula general de transformaciones y base decimal como intermedio: No me es claro el por qué la fórmula no es eficiente, si cuando realizamos el paso de hexa->binario en clase, ocupando dicha fórmula, no pasamos por la base decimal. Saluditos

**Comment by Geeermy** [comment]
@Dafnemami La fórmula general de transformación de bases transforma un número en base $b$ **a base decimal**, por eso no es eficiente. Lo que quiere decir el enunciado es que no queremos, por ejemplo, que hagas la transformación $b_{16} \rightarrow b_{10} \rightarrow b_{2}$, sino que tu algoritmo realice directamente la transformación $b_{16} \rightarrow b_{2}$, sin transformar tu número a una base intermedia (en el caso de la fórmula, base decimal).

Espero que quede más claro con eso.

¡Saludos!

**Comment by IgnAMS** [comment]
Hola! Respecto a esto mismo, tampoco se puede pasar a "otra base" conveniente (donde no es necesario usar la fórmula) diferente a la base 10?

**Comment by Geeermy** [comment]
¡Hola Nano! Tampoco sería óptimo, porque existen formas de hacerlo directo (aprovechando el hecho de que ambos números son de una base que es potencia de un mismo número $K$).

¡Saludos!
