### ISSUE TITLE
[T1 - P2.a] Se puede usar el comparador visto en clases como caja negra?

### ISSUE THREAD

**Issue by NicoJGutierrez** [IIC2343/Syllabus-2023-1#31]

**Comment by Geeermy** [comment]
¡Hola!

Solo puedes utilizarlo si realizas primero el diagrama en tu respuesta. No puedes asumir que "existe" solo porque hicimos un ejercicio en clases de él. Primero lo construyes y después indicas que usarás su abstracción para tu circuito final (una caja con el nombre que prefieras).

Recordatorio importante: recuerda que es un comparador de números enteros: Si $A = 3$ y $B = -4$, tu circuito debe indicar que $A > B$ (es distinto a la comparación de valor absoluto).

¡Saludos!

PD: Recuerda usar el formato indicado en el título de tu pregunta (prefijo [T1 - P2.a]).

**Comment by Geeermy** [comment]
Para las preguntas de circuitos eléctricos (ítem 2) no puedes usar componentes de almacenamiento de datos, tus diagramas deben corresponder a circuitos combinacionales. Si te refieres para preguntas del ítem 3 (almacenamiento de datos), ahí puedes usarlos (y cambiar, si lo deseas, la cantidad de bits a 8 o 16).
