### ISSUE TITLE
[T1 - P2.C] Problema con el número pasado para hacer los shifts.

### ISSUE THREAD

**Issue by NicoJGutierrez** [IIC2343/Syllabus-2023-1#32]
![image](https://user-images.githubusercontent.com/80768621/227799397-8da882d8-10a7-4364-a78b-44fd5033edd4.png)
Hola, para construír este compnente, si no me equivoco, se pide que el componente reciba número y que luego la cantidad máxima de shifts que se puedan hacer siguiendo ese número sea 16.

Input = número en 16 bits + número de shifts + dirección (?)
Output = número shifteado

El problema es que si se pide que sea un máximo de 16 operaciones shift representadas por un número. Si ese número está en 4 bits, va a llegar de 0 a 15, sin llegar al 16. Similarmente pasa para un número de 5 bits, que va a llegar de 0 a 31. 

Por esta razón me gustaría saber si puedo hacer que el número de shifts que puede hacer mi componente sea 15, para no tener que agregarle un bit adicional al número de entrada y retener la capacidad de indicarle a mi componente que haga 0 shifts.

(esto no debería ser un problema para el componente porque si haces los 16 shifts completos te quedan puros 0s, lo que no es realmente deseable)

**Comment by Geeermy** [comment]
¡Hola!

Primero: No es necesario que reciba como _input_ la dirección del _shift_, puedes elaborar una componente para _shift left_ y otra para _shift right_ (pero siéntete libre para hacerlas como prefieras).

Respecto a la cantidad de bits: puedes asumir que el número **siempre** será de 16 bits. Si solo usara 4 bits, puedes asumir que los otros 12 bits serán 0's.

Respecto al shift 0: La idea es que si pasas un número por la componente **sí o sí** se hará al menos un _shift_. El selector de _shifts_ no es necesariamente la cantidad de _shifts_ que harás. De esta forma, como tienes hasta 16 _shifts_ posibles, el esquema se verá de la siguiente manera:

| Bus de selección $S$  |  Resultado |
|---|---|
| 0000  | 1 _shift_  |
| 0001  | 2 _shifts_  |
| 0010  | 3 _shifts_  |
| 0011  | 4 _shifts_  |
| 0100  | 5 _shifts_  |
| 0101  | 6 _shifts_  |
| 0110  | 7 _shifts_  |
| 0111  | 8 _shifts_  |
| 1000  | 9 _shifts_  |
| 1001  | 10 _shifts_  |
| 1010  | 11 _shifts_  |
| 1011  | 12 _shifts_  |
| 1100  | 13 _shifts_  |
| 1101  | 14 _shifts_  |
| 1110  | 15 _shifts_  |
| 1111  | 16 _shifts_  |

Es cierto que con 16 _shifts_ tendremos solo una secuencia de 0's, pero el ejercicio no pide que este caso sea "útil" o "deseable", debe quedar así por construcción.

¡Saludos!
