### ISSUE TITLE
[T1 - P2.b] Duda con la ALU

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2343/Syllabus-2023-1#33]
Holaa 😸!

Para este inciso el circuito que cree debería estar dentro de la ALU, o yo puedo tomar solo el resultado de la ALU y en base a alguno circuitos que haga fuera de la ALU detecto y entrego si hay overflow o no.

Por otra parte, puedo considerar la ALU como un componente qu ya se conoce y no hacer los circuitos internos, o es requerido que igual los haga.

Saludos cordiales 😄 🐶.

**Comment by Geeermy** [comment]
¡Hola!

Puedes incluirlo dentro o fuera, no es relevante, pero sea cual sea el caso deberías: (1) considerar el resultado final de la operación seleccionada; y (2) considerar que la operación seleccionada sea de interés (suma o resta).

Respecto a la ALU en sí: Sí, puedes asumirla como una "caja negra", sin incluir los circuitos internos.

¡Saludos! 😄
