### ISSUE TITLE
[T1-2.c]

### ISSUE THREAD

**Issue by dchahuan** [IIC2343/Syllabus-2023-1#34]
Hola,
El cambio del shift left y shift right es con rotacion o remplazamos con zeros?

Gracias en anticipacion

**Comment by Geeermy** [comment]
¡Hola! Es con reemplazo de ceros. La rotación es solo para operaciones _rotate_ (y en el enunciado solo hablamos de _shifts_).

¡Saludos! :)

**Comment by Geeermy** [comment]
PD: Recuerda respetar el formato del título en las _issues_.

**Comment by dchahuan** [comment]
Gracias!!!
