### ISSUE TITLE
[T1-P2.C]  Duda cantidad de shifts

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2343/Syllabus-2023-1#37]
Hola 😸
Me surgió una duda respecto a la cantidad máxima de 16 shifts que se pueden hacer, se supone que yo recibo en binario la cantidad de shifts que se le quiere hacer al número que me están ingresando, o funcionaria de otra forma.

De antemano muchas gracias 👌

**Comment by Geeermy** [comment]
¡Hola!

Contesté esto en [esta _issue_](https://github.com/IIC2343/Syllabus-2023-1/issues/32#issuecomment-1484203611). En resumen: lo que recibirás en binario es una combinación que tú asocias a una cantidad de _shifts_. Por ejemplo, el bus `0000` puede indicar la realización de 1 _shift_, no es necesario que coincida el número en binario con la cantidad de _shifts_ (de hecho, como se aceptan de 1 a 16, no coincidirá). Puedes incluir una tabla de verdad para que quede claro cuántos _shifts_ realiza cada combinación. 😄 

¡Saludos!

**Comment by Mamunoz42** [comment]
Muchas gracias, no se si le podrían cambiar el nombre a esa issue, ya que esta mal el tag, dice que es pregunta 3 y por eso no la había visto.

Saludos 💯
