### ISSUE TITLE
[T1 - P1b] - Duda "bit de signo"

### ISSUE THREAD

**Issue by catalinacarter** [IIC2343/Syllabus-2023-1#38]
Hola! Cuando en el enunciado de la pregunta 1b se menciona "codificación (...) que utilice bit de signo", con bit de signo se refiere exclusivamente a respetar 0 - positivo, 1 - negativo, o podemos hacer una codificación que reformule esto, mientras se respete que haya un bit que represente el signo del número?
Muchas gracias :)

**Comment by frvalenzuela** [comment]
Hola Catalina,

Bit de signo significa que un bit representa positivo y otro negativo, no necesariamente el 0 debería ser positivo.

Saludos

**Comment by catalinacarter** [comment]
Super, muchas gracias! :)
