### ISSUE TITLE
[T1 - P3.d] Duda caso inválido

### ISSUE THREAD

**Issue by mjadresic** [IIC2343/Syllabus-2023-1#39]
Hola, no me queda claro si los dos casos:

Up=1, Down=1, Load=0, Reset=1 y Up=0, Down=0, Load=0, Reset=1 

deben preservar el estado o no, ya que si bien Up=1 y Down=1 o Up=0 y Down=0 preservan el estado, cuando Reset=1 y Load=0 si es un caso valido para reiniciar el contador, entonces no me queda claro quien predomina en estas situaciones.

**Comment by mjadresic** [comment]
En otras palabras, solo se podria resetiar cuando se este haciendo up/down?

**Comment by Geeermy** [comment]
¡Hola!

Lo que planteas es un caso **inválido** ya que estás diciendo que quieres incrementar, decrementar y resetear el valor del registro al mismo tiempo. Los únicos casos válidos en este contexto son:

| _Up_  | _Down_ | _Load_  | _Reset_ | 
|---|---|---|---|
| 0  | 0  | 0 | 0  |
| 1  | 0  | 0 | 0  |
| 0  | 1  | 0 | 0  |
| 0  | 0  | 1 | 0  |
| 0  | 0  | 0 | 1  |

Cualquier otra combinación implicaría que quieres realizar más de un cambio sobre el valor almacenado, que es lo que buscamos evitar. En resumen: solo se puede resetear si _reset_ es la única señal activa.

¡Saludos!

**Comment by Geeermy** [comment]
@mjadresic no sé por qué desapareció tu última duda, pero la respondo de todas maneras para evitar confusiones:

Las señales _Up_ y _Down_ **no son los flancos de subida y bajada**, son señales adicionales a los **contadores** que permiten incrementar ($Up = 1$) o decrementar ($Down = 1$) en una unidad el valor almacenado. En este caso, asumimos que la señal _clock_ (de flancos de subida y bajada) del componente no se toca, por lo que no debes preocuparte de ella.

¡Saludos!

**Comment by pabloalvarez67** [comment]
Hola! en el caso de que Load = 1 y el resto 0, deberiamos almacenar el valor Din en el registro? 
Y estan estos casos correctos teoricamente?
* Up = 1 y el resto 0 -->  Almacenamos Q + 1 (el valor que estaba antes en el registro + 1)
* Down = 1 y el resto 0 --> Almacenamos Q -1 (el valor que estaba antes en el registro - 1)

**Comment by Geeermy** [comment]
@pabloalvarez67 Exacto. Esos son los comportamientos esperados. Faltaría además considerar el caso $Reset = 1$ y todas las otras señales iguales a cero, donde el estado del contador cambia a cero.

¡Saludos!

**Comment by Mamunoz42** [comment]
Hola @Geeermy! No entiendo por que razón cuando Up = 1 y Load = 0 y Reset = 0 se considera como caso válido, ya que le que le estoy diciendo que aumente 1, pero no le estoy especificando que haga Load de este.

**Comment by Geeermy** [comment]
El problema está en que lo estás pensando como un registro, pero te recuerdo que el componente es un **contador**. Si $Up = 1$ estoy diciendo que incremente en una unidad **su valor almacenado**, que es distinto de $Load$ que indica que se cargue el **dato de entrada** (que perfectamente puede ser distinto al valor del contador).

Por ejemplo, si mi contador posee el valor 31 (por poner un número), poseo dato de entrada 14 y tengo $Up = 1$, entonces al llegar al flanco de subida el contador actualizará su valor a 32. En cambio, si hubiera tenido $Load = 1$, el contador habría actualizado su valor a 14 en el flanco de subida. No necesito que la señal $Load$ esté activa para actualizar el valor del contador, $Up$ y $Down$ por sí solos también lo cambian (y lo puedes corroborar en el diagrama de la clase 3 de mi sección, diapositiva 71/82).

¡Saludos!
