### ISSUE TITLE
Control parte 1 pregunta 3

### ISSUE THREAD

**Issue by NicoJGutierrez** [IIC2343/Syllabus-2023-1#4]
El enunciado es este:

![image](https://user-images.githubusercontent.com/80768621/227064409-cdc7cb59-6a6b-412f-92a3-cd9fc9381ffe.png)

Con **algoritmo** se refiere a una serie de pasos, a una fórmula, a un proceso con los conectores lógicos vistos en el curso o a algo escrito en seudocódigo?
Cuáles de esas opciones son viables para responder?

**Comment by frvalenzuela** [comment]
Hola Nicolás!

Lo preferible sería un seudo-código, dado que se entiende de mejor forma. Pero también con una serie de pasos mientras seas claro y quién te corrija no sufra ninguna ambigüedad al hacerlo no habrá problema.

Entre más explicada y justificada tu respuesta mejor, recomiendo dar ejemplos de como aplicarías tu algoritmo para que sea aún más entendible.

Si algo no quedo claro no dudes en consultarme.

Saludos!
