### ISSUE TITLE
[T1 - P1.a] Demostración

### ISSUE THREAD

**Issue by conyortizsimpson** [IIC2343/Syllabus-2023-1#40]
Hola!

Mi duda es qué tan matemáticamente o cómo se consideraría correcto demostrar que encontramos una representación posicional como las que nos piden en la pregunta.

Muchas gracias!

**Comment by Geeermy** [comment]
¡Hola!

Más que demostrar, necesitamos que **muestren** que su representación es efectivamente equilibrada. Pueden hacer una comparativa, por ejemplo, con 4 dígitos en la representación escogida vs. 4 dígitos en representación binaria con complemento de 2 y evidenciar que la suya sí es equilibrada. Pueden mostrar después que con un dígito más se sigue comportando de esa manera, no necesitamos demostraciones con inducción ni nada por el estilo.

Mientras esté bien explicado todo (es decir, que no simplemente enuncien la representación y digan que es equilibrada porque sí), estará correcto. :)

¡Saludos!

**Comment by Dafnemami** [comment]
@Geeermy y para mostrar que la base es equilibrada necesitamos también saber (y mostrar) cómo se obtiene su complemento?

**Comment by rosariodominguezm** [comment]
Pero me queda una duda de la pregunta. ¿Tengo que encontrar una representación que funcione para toda base "b"? ¿O solamente encontrar alguna forma equilibrada que dependa de un "b"?

Como que no me queda claro qué me piden.

**Comment by frvalenzuela** [comment]
Hola @rosariodominguezm ,

No es necesario para todo tipo de base "b", pero si caracterizar las bases que cumplan dicha condición. Una sola base que cumpla dicha condición no es suficiente.

Saludos!
