### ISSUE TITLE
[T1-P2.a] Nivel de detalle en los circuitos 

### ISSUE THREAD

**Issue by tzehnder** [IIC2343/Syllabus-2023-1#41]
Hola! tengo una duda de hasta que punto se debe entrar en detalle sobre los componentes del circuito, por ejemplo, si utilizo un full adder, el cual contiene half adders, debo especificar los componentes del half adder tambien?

**Comment by Geeermy** [comment]
¡Hola!

Lo importante son las señales y compuertas que realizan lo solicitado por el ejercicio. Para la pregunta 2 puntualmente, no hay problema con que utilices _half-adders_, _full-adders_, multiplexores, sumadores/restadores e incluso la ALU. Lo que se restringe para las preguntas del ítem 2 son componentes de almacenamiento (latches, flip-flops, registros, contadores, memorias) y componentes que hayamos hecho a modo de ejercicio y no de materia (si tienes duda con respecto a uno puntual, puedes consultar).

¡Saludos! :)

**Comment by Geeermy** [comment]
@josefinacortes Sí, no hay problema con que usen sumadores y restadores siempre que indiquen bien en la "cajita" que son dichas componentes. :)

¡Saludos!

**Comment by martin-santiago** [comment]
@Geeermy hola buenas, no me quedó claro, entonces puedo utilizar una alu como componente mencionando obviamente que fue vista en clases ¿?

**Comment by Geeermy** [comment]
@martin-santiago Sí, con la salvedad de que **no** pueden usar las _flags_ $Z, N, C, O$ (que son señales que, en el fondo, se construyen a partir de los circuitos que les pedimos elaborar).

Probablemente no necesiten usar todas las operaciones de la ALU en todo caso, por eso les podría servir una de más bajo nivel puntualmente... pero siéntete libre de usarla si así lo deseas.

¡Saludos!

**Comment by berrazuriz3** [comment]
@Geeermy Hola, a mí no me queda tan claro una cosa de esta pregunta, para que el circuito detecte que un número A es mayor a B o detectar la ocurrencia de overflow se puede decir: "Ya que el cable X después de la operaciones del circuito es 1, entonces existe overflow"? O se tiene que explicar que el circuito está conectado a algún sistema aparte?

**Comment by Geeermy** [comment]
@berrazuriz3 Sí, puede (y de hecho, debe) ser un cable final que transmita un bit que indique si hubo _overflow_ (bit = 1) o no (bit = 0). No es necesario conectarlo a ningún otro tipo de sistema, solo nos importa la señal final que nos da la respuesta (con el cable que mencionas).

¡Saludos!
