### ISSUE TITLE
[T1-2.D] Duda valor "17" en update_seed

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2343/Syllabus-2023-1#42]
Hola! en esta función el valor de S, número binario de 16 bits, se multiplica por 17 y luego se le suma 1 para actualizar el valor.
Ese 17 siempre será ese número en binario de 16 bits? vale decir, es lo mismo que hacer: 
S * 0000000000010001 ? (este es el 17 decimal representado en binario de 16 bits).

Saludos!

**Comment by Geeermy** [comment]
¡Hola!

Sí, puedes asumir que será ese número en 16 bits. Es una constante.

¡Saludos!

**Comment by pabloalvarez67** [comment]
> ¡Hola!
> 
> Sí, puedes asumir que será ese número en 16 bits. Es una constante.
> 
> ¡Saludos!

Perfecto! es válido usar nuestras componentes shift-left y right de la pregunta 2.C para agilizar la respuesta? Gracias.

**Comment by Geeermy** [comment]
@pabloalvarez67 Edité tu pregunta ya que no es la idea dar soluciones dentro de las _issues_... no obstante, sí, de hecho los instamos a considerar los componentes que ya han construido en esta misma tarea, algunos podrían ser de utilidad. ;)

¡Saludos!
