### ISSUE TITLE
[T1 - P1.a] Complemento en b!=2

### ISSUE THREAD

**Issue by Dafnemami** [IIC2343/Syllabus-2023-1#44]
Hola!,

No me es claro como generar un equivalente al complemento a dos en representaciones posicionales cuya b sea distinta de 2.

🚗

**Comment by Geeermy** [comment]
¡Hola!

El algoritmo de "complemento de $b$" se basa en encontrar el número en representación base $b$ que, al ser sumado con el número original, te entrega el número 0 (una secuencia de 0's) y un _carry_ que no alcanza a ser parte de la secuencia al exceder la cantidad de dígitos utilizada. En clases (para base binaria), la construcción la hacemos "negando" cada bit y sumando una unidad al resultado, pero la negación es equivalente a la resta entre cada dígito de la secuencia y el dígito de mayor valor de la base ("1" en base 2), que sería la obtención del complemento. Si lo extiendes a una base distinta, te darás cuenta que la construcción es la misma pero realizando restas con números de valores mayores.

Tomemos de ejemplo el "complemento de 4" del número 0123 en base 4 (donde el dígito "3" es el de mayor valor en esta representación):

$$C_4(0123) = (3-0)(3-1)(3-2)(3-3) + 0001 = 3210 + 0001 = 3211$$

Si hacemos la suma: 

$$0123 + 3211 = (1_{carry})0000$$

Cumplimos lo pedido. En la clase 1 de la sección 2, puedes ver la diapositiva 24/44 donde se explica el origen del nombre "complemento de 2" y un ejemplo. Esta diapositiva, de hecho, la incluí por la pregunta que hiciste tú en clases. 😎 

Si necesitas más información o ejemplos, te sugiero buscar por el "método de complementos" o "method of complements" y "radix complement". 😄 

¡Saludos!

**Comment by Dafnemami** [comment]
Y el tema de la suma de un bit, cuál es la razón de ser de eso? más allá de que nos damos cuenta de que funciona y por eso lo ocupamos.

**Comment by frvalenzuela** [comment]
La razón es que nos permite identificar el llamado elemento neutro, como una representación númerica identica a cero. Esto ayuda a realizar operaciones aritmeticas con representaciones posicionales de forma más consistente.

Saludos!

**Comment by Dafnemami** [comment]
cómo? no me es muy clara la respuesta, podría pedirte una aclaración más larga? ugu

**Comment by Geeermy** [comment]
@Dafnemami ¿Me podrías explicar un poco más tu pregunta? ¿Te refieres a la razón de ser del complemento de 2? Porque siguiendo mi ejemplo anterior, se realiza exactamente lo mismo. Tomemos el complemento de 2 de 0101 (en este caso, el dígito de mayor valor es "1"):

$$C_2(0101) = (1-0)(1-1)(1-0)(1-1) + 0001 = 1010 + 0001 = 1011  $$

Si hacemos la suma del número original con su "complemento de 2":

$$ 0101 + 1011 = (1_{carry})000 $$

Entonces, hacemos uso de esta representación de negativos porque **aritméticamente** se cumple que $A + (-A) = 0$, considerando que el bit de _carry_ sobrante **se elimina** al exceder la cantidad de dígitos permitidos. Esto es independiente de la base, se cumple siempre para los complementos de 2, de 3, de 4, etc. tal como indiqué en el ejemplo anterior.

Ahora, puntualmente usamos complemento de 2 en el curso porque es el complemento asociado a la base binaria (base 2), que es la que usamos en el computador básico por su traducción directa a circuitos digitales a través de la lógica booleana.

Si sigues con dudas, siéntete libre de seguir preguntando por este hilo. :)
