### ISSUE TITLE
[T1 - P3.A] Retraso de propagación

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2343/Syllabus-2023-1#45]
Hola! la frecuencia de estos flip-flops depende del retraso de propagación de cada uno.
Podemos asumir que este es insignificante o tenemos que considerarlo?
Además, la señal del clock es la misma para todos los flip-flop?

**Comment by Geeermy** [comment]
¡Hola!

1. Puedes asumir que no hay retraso de propagación.

2. No. Si te fijas bien en el dibujo, el _clock_ del segundo flip-flop es la salida $Q$ del primero; el _clock_ del tercer flip-flop es la salida $Q$ del segundo y así sucesivamente hasta $N$.

¡Saludos!
