### ISSUE TITLE
[T1 - P3.C] valores Reset y Load

### ISSUE THREAD

**Issue by nicogrecod18** [IIC2343/Syllabus-2023-1#46]
Hola, tengo una duda con Reset y Load. Entiendo que cuando load es 1, se permite que se actualicen los flip flops del registro y cuando es 0, nunca llega la señal C a los flip flops. Por otro lado, no me queda muy claro el Reset, ya que me lo abría imaginado que cuando vale 1 todos los flip flops se actualizan con el valor 0, sin embargo para esto el load debería estar en 1 también.

En el enunciado se menciona lo sguiente: "que la combinación de señales Load = 1, Reset = 1 preserve el estado del registro". Mi pregunta es ¿Reset funciona independientemente de Load ? es decir, ¿Si Reset es 1 y Load es 0, se actualizan igual a 0 los flip flops?

¿o Reset necesita de que Load sea 1 para actualizar los flip flops? Es que de ser así, no tendría sentido el enunciado.

De antemano muchas gracias.

**Comment by nicogrecod18** [comment]
Muchas Gracias !!

**Comment by pabloalvarez67** [comment]
Hola! yo no entiendo muy bien lo que se nos pide.
comprendo la explicación del Register visto en clases, pero a que se refiere con que se preserve el estado de registro?
que no entre ninguna información al D del flip-flop? (vale decir, no se resetea a 0, ni le llega la info del MUX, la cual puede ser el valor actual de Q o el dato de entrada.

saludos!

**Comment by Geeermy** [comment]
@pabloalvarez67 Se refiere a preservar el estado $Q$ (es decir, como si tuvieras $Load = 0, Reset = 0$. Si te fijas en el diagrama que compartí arriba, actualmente si $Load = 1, Reset = 1$, el resultado de la compuerta AND será un 0 y será lo que se almacene en el flip-flop (y aplicará de la misma forma en todos los flip-flops del registro). Queremos que $Load = 1, Reset = 1$ **también** preserve el estado, ya que es una combinación de señales que consideramos inválida y que, por lo mismo, queremos que no tenga efecto alguno en el valor almacenado.

Espero que se entienda ahí 🙏

**Comment by Mamunoz42** [comment]
Hola, aquí me surge una duda, porque el diagrama que se ve en las diapositivas indica que cuando el Load = 1 se selecciona el D de entrada, mientras que cuando Load = 0, ahí se almacena el Q, entonces en ese caso también hay que modificar el Mux?

Saludos 😄

**Comment by Geeermy** [comment]
@Mamunoz42 Puedes modificar lo que sea necesario para lograr lo pedido. Si tus cambios no afectan al resto de componentes internos, no es necesario que los cambies.

Por favor, recuerda no incluir información que aluda a una respuesta de la pregunta.

¡Saludos!
