### ISSUE TITLE
[T1 - P2.b] El carry cuenta como overflow?

### ISSUE THREAD

**Issue by IgnAMS** [IIC2343/Syllabus-2023-1#47]
Hola! Si sumo -3 con -5 con 4 bits tendría que sumar las secuencias `1011` con la `1101` que daría como resultado `11000` y que se convertiría en `1000` con un bit de carry y dando resultado -8. En este caso se va el 1 del carry porque no cabe, pero el resultado es coherente con lo obtenido. Este caso se considera overflow ya que no cabe el último 1? O solo consideramos overflow cuando el resultado es incoherente con lo pedido?

Saludos!

**Comment by Geeermy** [comment]
¡Hola Nano!

No, el _overflow_ específicamente aplica cuando el resultado **no es coherente**, lo que indicas es perfectamente válido y en dicho caso tu circuito debe retornar $overflow = 0$.

¡Saludos!

**Comment by IgnAMS** [comment]
Muchas gracias por la respuesta profe 🥳

Que tenga una buena noche!

**Comment by rosariodominguezm** [comment]
Hola! A mí me queda la duda de si hay alguna relación entre Carry y Overflow. Podría haber un ejemplo que tenga carry y overflow a la vez? O son excluyentes.

**Comment by Geeermy** [comment]
@rosariodominguezm ¡Hola! Son distintos y, finalmente, se diferencian según el uso.

En el ejemplo de esta _issue_, se activaría solo la _flag_ de _carry_ ya que la representación está ok, pero supongamos que hubiéramos sumado con -3 y -6 en representación **con signo** de 4 bits:

$$1101 + 1010 = (1_{carry})1111$$

En este caso, tengo tanto el _carry_ activo (porque lo hubo como resultado de la suma) como el _overflow_ activo porque la secuencia `1111` corresponde al número -1 en representación binaria de 4 bits **con signo**. 

El _carry_ suele ocuparse más en representación **sin signo**, porque este indica **explícitamente** que hubo un bit que no pudo usarse (porque excede la cantidad de bits).

En resumen: son distintos, se usan con distintos motivos y en el caso de esta pregunta (2.b), solo debes preocuparte del _overflow_.

¡Saludos!

**Comment by rosariodominguezm** [comment]
Ya perfecto! Ahí igual queda (1)0111, pero entendí la idea! Gracias!!

**Comment by Geeermy** [comment]
Whoops. Gracias por la corrección. :)

**Comment by diegocostares** [comment]
@Geeermy Hay que considerar el complemento a uno o el complemento a dos?

**Comment by Geeermy** [comment]
@diegocostares Complemento de dos. Es la representación que usamos siempre para trabajar con valores negativos en circuitos eléctricos.

¡Saludos!
