### ISSUE TITLE
[Proyecto - Etapa1] Duda: Diagrama ROM

### ISSUE THREAD

**Issue by martin-santiago** [IIC2343/Syllabus-2023-1#48]
Hola

Tengo una duda con la implementación del componente ROM, en el caso de la CPU se nos dá un diagrama interno con el que podemos deducir que compuertas usa cada componente de este, pero para la ROM solo tenemos sus inputs y outputs del primer diagrama, pero no entendemos mas allá que eso, por lo que andamos un poco perdidos de qué hacer respecto a la ROM ya que en el enunciado se señala que debemos trabajarla de algún modo.

gracias de antemando :)

**Comment by R0W5tortion** [comment]
Hola

La ROM ya está implementada, si se van al archivo verán que hay un arreglo con `4K = 4 * 1024 = 4096` elementos, por lo que su ROM tiene un tamaño de 4KB. Como cada entrada es de 36 bits, el mismo tamaño que la palabra que tienen que definir ustedes, lo que tienen que hacer es reemplazar las entradas de la ROM con las instrucciones en binario del programa que están intentando cargar

Espero les haya quedado más claro. Saludos y éxito con esto y la tarea
