### ISSUE TITLE
Control 1 pregunta 2.b

### ISSUE THREAD

**Issue by NicoJGutierrez** [IIC2343/Syllabus-2023-1#5]
Hola, en la pregunta 2.b entiendo que cuando se suman números enteros con complemento a 2 existe un overflow que no indica necesariamente que los datos hayan excedido un límite. Ese overflow debe mostrarse como tal o no?

**Comment by frvalenzuela** [comment]
Hola Nicolás,

Para responder en completitud esta pregunta debería ondar en la solución de la misma, cosa que no puedo hacer. Pero puedo decir que _overflow_ se refiere a lo siguiente (citando los apuntes del curso):

> ...en operaciones de número con signo, cuando ocurre un **overflow** es decir cuando una operación que debía resultar en un número positivo resulta en un número negativo o viceversa.

Se espera que tu circuito pueda detectar los casos donde esa definición se cumpla.

Saludos!
