### ISSUE TITLE
[T1 - P3.d] Componentes

### ISSUE THREAD

**Issue by IgnAMS** [IIC2343/Syllabus-2023-1#52]
Hola! En la pregunta P3.D podemos usar estructuras como 4-muxers? Que creo que lo hace harto más sencillo, pero no estoy seguro si se busca este tipo de componentes. 

Saludos!

**Comment by Geeermy** [comment]
¡Hola Nano!

Sí, ningún problema con usar multiplexores de _N_ entradas, solo asegúrate de indicar bien la cantidad de bits de selección en cada caso.

¡Saludos!

**Comment by IgnAMS** [comment]
Gracias 🥳!
