### ISSUE TITLE
[T1 - P3.(c y d)] Qué componentes puedo usar como cajas negras?

### ISSUE THREAD

**Issue by NicoJGutierrez** [IIC2343/Syllabus-2023-1#53]
Hola, el registro de 4 bits y el contador de 4 bits los tengo que armar por mi cuenta para responder la pregunta, o los puedo tratar como caja negra? 

Desde qué punto puedo usar componentes? Puedo por ejemplo usar un latch D como caja negra? Qué tal un latch JK? Puedo abstraerlos para n bits automáticamente?

**Comment by Geeermy** [comment]
¡Hola Nico!

Puedes tratarlos como caja negra o puedes ver las construcciones que vimos en clases y hacer las modificaciones desde ahí, ambas opciones son válidas.

Para estas preguntas también puedes usar flip-flops como caja negra sin problemas (y del tipo que quieras), siempre que esté explicado y justificado su uso. Lo que sí, no pueden ser de $N$ bits, solo pueden almacenar un estado. Si quieres almacenar $N$ bits, necesitas $N$ flip-flops.

Por último: recuerda que los registros y los contadores funcionan con flancos de subida... si los construyes solo con latches, perderían esta característica y no cumplirías con tener un registro o un contador como tal. Asegúrate de usar flip-flops y no latches.

¡Saludos!
