### ISSUE TITLE
[T1] Fecha máxima para pedir cupón

### ISSUE THREAD

**Issue by sebacarrasco** [IIC2343/Syllabus-2023-1#54]
Holaa, ¿hasta cuándo se puede llenar el form para usar cupones de atraso?

**Comment by frvalenzuela** [comment]
Hola Sebastián!

Para hacer uso del cupón, hasta el mañana a las 20 horas. Luego pueden actualizar su respuesta si es que llegan cerca al horario límite y se dan cuenta que necesitan usar más de uno. Las tareas serán retiradas el jueves 13, que será hasta cuando tengan fecha para actualizar su respuesta.

Saludos!
