### ISSUE TITLE
[T1-P2C] Tablas de verdad

### ISSUE THREAD

**Issue by criism0** [IIC2343/Syllabus-2023-1#55]
Holaa! quería consultar respecto a como debemos escribir una tabla de verdad para las componentes de shifts, ¿debemos hacerlas similar a la que vimos en el laboratorio 2?, entendiéndolo como una asignación "lógica"  posicional o debemos escribirlas y pensarlas de otra manera?

**Comment by frvalenzuela** [comment]
Hola! 

La pregunta solo pide construir el componente, no es necesario establecer la tabla de verdad. 

Si la quieres agregar puedes hacerlo como la tabla de verdad para la ALU que vimos en el laboratorio 2, pero lo más importante es el diagrama del componente más que su tabla. 

Saludos !
