### ISSUE TITLE
[Entrega1] Mux PC en el diagrama general en clases pero no en el enunciado.

### ISSUE THREAD

**Issue by NicoJGutierrez** [IIC2343/Syllabus-2023-1#57]
Este es el enunciado del proyecto etapa 1:
![image](https://user-images.githubusercontent.com/80768621/230727404-a0ff3eb0-18e0-4ae5-b386-0489372b1cd9.png)
Y esta es la arquitectura vista en clases:
![image](https://user-images.githubusercontent.com/80768621/230727478-2c219b48-edf2-4fa8-b494-eed17cd1b51f.png)
Qué hago con el mux PC?

**Comment by frvalenzuela** [comment]
Hola @NicoJGutierrez !

Ese selector se utiliza para la instrucción RET que no es soportada en la primera etapa del proyecto. En la próxima etapa deberán agregarlo.

Saludos!
