### ISSUE TITLE
[T1 - P3.d] Componentes

### ISSUE THREAD

**Issue by martin-iturralde** [IIC2343/Syllabus-2023-1#58]
Hola,
Se puede usar el bus del registro como en clases o lo tengo que describir por dentro?
Es decir puedo poner Registro de 4 bits sin tener que explicarlo?
Gracias!
Pd: si R = 0, entonces el registro queda como nuevo valor 0?

**Comment by frvalenzuela** [comment]
Hola @martin-iturralde ,

Cuidado con lo que subes por este medio, mandar soluciones parciales es una falta a la integridad acádemica. Respondiendo a tu duda, si puedes ocupar el registro sin tener que describirlo por dentro, y cuando R = 1 queda como 0.

Saludos!

**Comment by martin-iturralde** [comment]
Disculpa por la imagen, pero de cualquier modo, es lo que está en las clases de la sección 2. No es nada mío.
Dicho eso, lo que sigo sin entender es que dado el Registro cada vez que R = 1, se va resetear el contenido del Registro. El R es muy determinante en la parte final del Registro por lo que, sin importar cuanto valgan los otros (Down, Up y Load) el resultado se reseatea.
En síntesis, si se usa el Registro como caja negra entonces no se podría cumplir lo que piden.

**Comment by Geeermy** [comment]
¡Hola @martin-iturralde!

Justamente eso es lo que pedimos que controles. Puedes hacerlo tratando el registro como una caja negra y controlando el valor de la señal $R$ según el valor de las otras señales, o bien puedes trabajar a nivel interno si es que se te hace más fácil controlarlo así. De todas formas, lo que dices es justamente lo que pasa actualmente y lo que queremos que, en este ejercicio, se evite.

¡Saludos!
