### ISSUE TITLE
[T1 - P3.d] Inputs inválidos con señal RESET

### ISSUE THREAD

**Issue by martin-santiago** [IIC2343/Syllabus-2023-1#59]
Hola, tengo una duda con algunos inputs, por ejemplo,

| down | up | L | R | Dout |
|------|----|---|---|------|
| 1    | 1  | 0 | 1 | ?    |
| 1    | 0  | 0 | 1 | ?    |
| 0    | 1  | 0 | 1 | ?    |

En estos casos, puedo tomar en cuenta que la señal de RESET tiene prioridad ante todo y dejar Dout en 0?, o debo tomarlos también como inputs inválidos y dejar el valor previo en Dout?¿

**Comment by Geeermy** [comment]
¡Hola!

Todos esos casos también son inválidos. Ninguna señal tiene prioridad por sobre la otra, lo que debes hacer es que esto no pase y que el cambio sobre $D_{out}$ ocurra si, y solo si **solo una** de las señales está activa.

Puedes referirte [a la respuesta de esta _issue_](https://github.com/IIC2343/Syllabus-2023-1/issues/39#issuecomment-1487511037) para ver los únicos casos válidos en los que se modifica el estado interno del contador.

¡Saludos!
