### ISSUE TITLE
[T1 - Pregunta 2.b]  Podemos asumir que la ALU es solo un sumador/restador?

### ISSUE THREAD

**Issue by juanluis2019** [IIC2343/Syllabus-2023-1#6]
En la Pregunta 2.b podemos asumir que estamos trabajando con una ALU de 8-bits que solo suma y resta?. O tenemos que considerar que la ALU hace las 8 operaciones básicas: SUMA, RESTA, AND, OR, NOT, XOR SHIFT L, SHIFT R?
Gracias

**Comment by Geeermy** [comment]
¡Hola! Germán aquí (profe sección 2). :) Por fis, recuerda incluir el _label_ en tu _issue_ indicando que es una pregunta de la tarea.

Respondiendo tu pregunta: No, tienes que asumir que es la ALU que realiza las 8 operaciones, por lo que tu circuito debe poder identificar la operación que se está llevando a cabo y, así, poder evaluar bien o no si existe o no _overflow_.

¡Quedo atento por si tuvieras más dudas!

**Comment by Geeermy** [comment]
Adicionalmente: Si tienes dudas sobre las señales de selección para la operación, puedes asumir $S = 000 = add$ y $S = 001 = sub$

**Comment by Geeermy** [comment]
PD: Cuando te dije que añadieras el _label_, me refiero aquí, seleccionando la etiqueta `Tarea1`:

<img width="342" alt="Captura de Pantalla 2023-03-24 a la(s) 10 13 48" src="https://user-images.githubusercontent.com/5559611/227530670-e4a04e64-f795-418e-b301-d4cf3d22d1b3.png">

**Comment by juanluis2019** [comment]
Gracias por la aclaración!

No me da la opción de poner una etiqueta :(

**Comment by frvalenzuela** [comment]
Ahora se agregara de forma automatica si ponen bien el titulo 

Saludos!

**Comment by josefinacortes** [comment]
Sobre la ALU, ¿Podemos utilizar que tiene dos salidas? ¿Los C,Z,N vistos en el laboratorio y el resultado? En los diagramas de clase pareciera que tiene solo la salida del resultado. Gracias!

**Comment by frvalenzuela** [comment]
Hola @josefinacortes,

En caso de querer ocupar la ALU vista en el laboratorio, deben diagramar el comportamiento interno, no pueden asumir caja negra el como hicieron las señales C, Z y N.

Saludos!

**Comment by Mamunoz42** [comment]
En caso de que la operación no sea ninguna de las que nos importan hay que retornar la flag de Overflow como 0?

**Comment by frvalenzuela** [comment]
Si, pueden retornar como cero en operaciones irrelevantes como las lógicas. 

Saludos !
