### ISSUE TITLE
[Proyecto - Etapa 1] Duda: índices de la ROM

### ISSUE THREAD

**Issue by pedroriosg** [IIC2343/Syllabus-2023-1#61]
Hola! Quería saber sí los índices de la ROM parten en 0 o en 1 (esto para hacer el JUMP a esa línea.

También quería saber si al hacer el JUMP, la línea a la que se debe saltar tiene que ir en binario en los 12 bits que entran al PC  o se hace de otra forma? Estoy medio perdido con eso.

Muchas gracias!

**Comment by frvalenzuela** [comment]
Hola @pedroriosg !

Parten desde cero. Efectivamente, debes usar los 12 bits menos significativos de los 16 que salen de la ROM y que se ocupan como literal.

Espero que te sea de utilidad, si tienes alguna consultas me dices.

Saludos!
