### ISSUE TITLE
[T2 - P1. a] Diagramas de modificaciones

### ISSUE THREAD

**Issue by martin-iturralde** [IIC2343/Syllabus-2023-1#65]
Cuando nos piden modificar el diagrama es modificarlo para que todos los casos se cumplan de una vez, o es un diagrama por caso?

**Comment by Geeermy** [comment]
¡Hola Martin!

Es un diagrama para todos los casos. Es decir, el diagrama que incluyas debe ser capaz de ejecutar, por ejemplo, estas instrucciones en un solo programa:

```
MOV B,(A)
INC A
MOV B,(A)
```

Ojo que debe seguir siendo capaz de ejecutar las otras instrucciones de direccionamiento indirecto, por ejemplo:

```
MOV A,(B)
MOV B,(A)
```

¡Saludos!
