### ISSUE TITLE
[Proyecto - Etapa 1] Duda: Instanciar Reg

### ISSUE THREAD

**Issue by criism0** [IIC2343/Syllabus-2023-1#66]
Holaa! tengo una duda con como instanciar Reg A y Reg B en nuestro CPU ya que si bien las componentes inicialmente indican "no tocar", el diagrama muestra 3 entradas y una salida por cada una de las componentes, entonces no sé exactamente qué debo hacer para instanciar correctamente las componentes.

**Comment by R0W5tortion** [comment]
Para las señales de entrada pueden ponerle números fijos. Por ejemplo, si al instanciar ponen `up => '1'`, en cada ciclo el valor guardado subirá en 1 *a menos* que en ese ciclo el `load` sea 1 (hint: habrá alguna componente que *necesitan* que tenga este comportamiento?). Entonces, se puede usar la misma componente, instanciada de distintas formas, para hacer las 4 componentes de la CPU que necesitan guardar información

Dicho esto, el NO TOCAR es más un warning para ustedes; pueden hacer modificaciones, pero es bajo su propio riesgo. De hecho, en la entrega 2 van a agregar un componente para el que probablemente tengan que hacerle una modificación, o sino tendrían que hacer malabares entre el proyecto y el ensamblador para que el `clear` funcione correctamente.

Saludos
