### ISSUE TITLE
[Proyecto - Etapa1] Opcodes invalidos y termino de programa

### ISSUE THREAD

**Issue by Jpuc1143** [IIC2343/Syllabus-2023-1#68]
Hola! Que tenemos que hacer si se recibe un opcode invalido? Queda a discreción nuestra?

¿Que se hace para el fin de programa? Si se deja corriendo el programa al terminar eventualmente el PC deberia hacer overflow y empezar la ejecuccion del programa nuevamente. Debemos evitar esto de alguna manera? Por ejemplo, añadir un loop infinito al final del assembly o implementar una instrucción que para la ejecucción de la cpu.

**Comment by R0W5tortion** [comment]
Hola. El opcode lo definen ustedes, por lo tanto, si llega un opcode invalido es culpa suya. Nosotros nunca vamos a pedir que corran un binario que definimos nosotros, siempre serán instrucciones en Assembly que ustedes tienen que traducir

Respecto al fin del programa, pueden hacer un
```
end:
  JMP end
```
al final, o pueden rellenar con NOPs las otras ~4000 lineas de la ROM (si su NOP es "00000000 00000000 00000000 00000000" ni siquiera tienen modificar estas). Como el clock esta en modo super lento, no van a alcanzar a correrse todas las instrucciones y va a parecer como si la placa esta *en pausa*

Saludos
