### ISSUE TITLE
Consulta CPU señal "dis"

### ISSUE THREAD

**Issue by Rocio356** [IIC2343/Syllabus-2023-1#69]
Hola, nos dimos cuenta de que la CPU tiene una señal de salida llamada "dis" que no vemos en el diagrama. Es importante?
Muchas gracias

**Comment by frvalenzuela** [comment]
Hola Rocio! 

Si es importante, porque es la señal que se conectará con los registros. Eso permitira ver el valor de los mismos en el display de 7 segmentos. Si no lo conectan, su presentación se verá afectada negativamente. 


Saludos!
