### ISSUE TITLE
[T1 - Pregunta 2.a] Por números enteros entiendo {-2, -1, 0, 1, 2} representados en complemento de dos. Esta bien?

### ISSUE THREAD

**Issue by juanluis2019** [IIC2343/Syllabus-2023-1#7]
Hola,
En la pregunta 2.a se habla de numero entero. Por numero entero se refieren al conjunto {-2, -1, 0, 1, 2} (los Z) en representación en complemento de 2?
Gracias

**Comment by Geeermy** [comment]
¡Hola!

Sí, básicamente el comparador debe funcionar con números positivos y negativos en base 2 (o binarios), siendo los negativos representados por complemento de 2 (por lo que, naturalmente, el bit más significativo indica el signo).

Recuerda que el ejercicio plantea que el comparador funcione para $N$ bits.

¡Éxito!
