### ISSUE TITLE
Consulta señal INC A y DEC A

### ISSUE THREAD

**Issue by AlonsoZamorano** [IIC2343/Syllabus-2023-1#70]
Hola!
Por un error de tipeo tuve que rehacer mis opcodes y me di cuenta de que no entiendo como manipular las señales para obtener las instrucciones "INC A" y "DEC A" ya que por lo que entiendo del esquema básico necesito de hacer uso de 2 ciclos para generar estas instrucciones (por lo que no se como traducirlo a señales de control).

**Comment by R0W5tortion** [comment]
Seguro que no hay alguna forma en que puedes hacer `A = A + 1` y `A = A + (-1)` (donde 1 y -1 son literales) con lo que ya tienes? Piénsalo

**Comment by AlonsoZamorano** [comment]
Yaaaa, entiendo. Muchas gracias!
