### ISSUE TITLE
[Proyecto - Etapa1] 

### ISSUE THREAD

**Issue by berrazuriz3** [IIC2343/Syllabus-2023-1#72]
![image](https://user-images.githubusercontent.com/101363118/232340221-d62b4a81-918c-430f-894e-9333fd9a599d.png)
 Me aparece este error pero no sé que puede ser para que pueda arreglarlo

**Comment by R0W5tortion** [comment]
Vivado es muy quejica con el path, lo he visto fallar por ejemplo con tildes y con path muy largos. No veo tildes en este caso, pero si se ve un poco largo, mira si se arregla al ponerla en una carpeta muy cerca de C:, como por ejemplo `C:/PA2/Proyecto Base...`

Y bueno, a veces todo se arregla solo con reiniar Vivado
