### ISSUE TITLE
[Proyecto - Etapa1] Inicializar valores

### ISSUE THREAD

**Issue by criism0** [IIC2343/Syllabus-2023-1#77]
Holaa, creo que tengo un problema que hace que no funcione nada de mi algoritmo y es como inicializamos los valores de los registros A y B con lo que queremos hacer, no sé donde se almacenan estos valores y como seleccionarlos para que estos sean usados luego.

**Comment by frvalenzuela** [comment]
¡ Hola Cristóbal !

Los valores puedes iniciarlos y almacenando con las instrucciones que hacen llamados a la memoria de datos.

¡Saludos!

**Comment by criism0** [comment]
pero como sé cuales valores iniciar en los registros

**Comment by frvalenzuela** [comment]
¡ Hola Cristóbal !

Son los valores que puedes definir en `DATA:`

¡Saludos!

**Comment by criism0** [comment]
Si, entiendo eso, pero donde encuentro los valores de DATA, estos debemos ponerlos con la placa?, se almacenan en algún lugar?, no entiendo a nivel de placa como llegan los valores desde lo que ponemos a nuestros registros

**Comment by frvalenzuela** [comment]
¡ Hola Cristóbal !

Como te comente anteriormente, puedes almacenar con las instrucciones que hacen llamados a la memoria de datos. Este tipo de instrucciones te permite almacenar en memoria. También puedes usar literales con instrucciones tipo `MOV`.

¡Saludos!
