### ISSUE TITLE
[T2 - P1.b] Agregar nuevo componente

### ISSUE THREAD

**Issue by jrvalenzuela** [IIC2343/Syllabus-2023-1#79]
Si quiero agregar una nueva componente al computador básico, qué tan detallada tiene que ser? puedo simplemente dibujar un cuadro que represente la componente y explicar como funciona? o tengo que construirla desde 0 con compuertas lógicas?

**Comment by Geeermy** [comment]
¡Hola!

Depende. Si es una componente ya conocida (_enabler_, multiplexor, registro, contador, etc.), no es necesario ya que se asume que conocen su comportamiento interno. No obstante, si fuera un componente con algunas modificaciones para que funcione de alguna manera distinta, ahí sí sería necesario que muestres un diagrama de este explicando cómo funciona antes de usarlo como caja negra dentro de tu diagrama.

¡Saludos! :)
