### ISSUE TITLE
[T2 - P3] Restricciones Assembly

### ISSUE THREAD

**Issue by JosefaPaz** [IIC2343/Syllabus-2023-1#80]
Hola!

Cuando en el enunciado dice _"Implemente en Assembly del computador básico visto en clases"_, no entiendo completamente cuáles son las limitaciones al hablarnos del computador básico para la implementación.

Gracias desde ya!

**Comment by Geeermy** [comment]
¡Hola Josefa!

Son solo las instrucciones que hemos visto en clases y que están habilitadas en el computador que diseñamos en las clases de "Programabilidad" y "Saltos y subrutinas". Puedes revisar en las _slides_ de la [clase 7, sección 2](https://cursos.canvas.uc.cl/courses/53215/files/7780910?module_item_id=1586996) (diapositivas 17 y 18) el listado completo de instrucciones habilitadas.

¡Saludos!

**Comment by pabloalvarez67** [comment]
Hola! tenia la misma duda, pero además, no me queda claro el enunciado con respecto a como el algoritmo opera sobre un *arreglo*, como este entraría a nuestro computador para que el algoritmo pueda interactuar con el?

Saludos!

**Comment by Geeermy** [comment]
¡Hola Pablo!

Los arreglos en Assembly se trabajan de la siguiente forma:

```
DATA:
  arr 7
        12
        4
        0
  len 4
CODE:
  MOV B,arr ;B = dirección primer elemento del arreglo arr.
  MOV A,(B) ;A = Mem[B] = primer elemento del arreglo arr.
  ... ; operaciones varias.
  INC B ;B += 1, siguiente dirección del arreglo.
  MOV A,(B) ;A = Mem[B] = segundo elemento del arreglo arr.
  ... ; etc.
```

Básicamente, definimos tanto el arreglo como su largo y después usamos métodos de direccionamiento para acceder a cada elemento de los arreglos. El _assembler_ es el que se encarga de que todos los elementos del arreglo queden en direcciones contiguas para poder operar de esa forma. Agregamos también el largo para poder definir cuándo terminar de recorrerlo. Pueden agregar variables adicionales si así lo desean para facilitar el desarrollo de su algoritmo (en las clases de Programabilidad y Saltos y subrutinas dejé algunos ejemplos). :)

¡Saludos!
