### ISSUE TITLE
[T2 - P1.a] Cantidad de entradas en un registro

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2343/Syllabus-2023-1#81]
Hola! en la modificación de nuestro pograma, existe algún límite de entradas que puede recibir un registro?

**Comment by Geeermy** [comment]
¡Hola!

¿Te refieres al "dato de entrada" de un registro? En ese caso, sí, solo puede recibir una entrada. No obstante, si quieres tener la opción de escoger uno de varios valores a cargar sobre un registro, puedes hacer uso de un **multiplexor**. Por ejemplo, si revisas puntualmente el componente `Mux PC` en el computador básico con saltos, puedes ver que este nos da la opción de cargar sobre el registro `PC` uno de dos valores: el literal (usado para saltos) y un valor leído de la memoria de datos (usado para la dirección de retorno de una subrutina).

Espero que se entienda la idea. 🙏 

¡Saludos!
