### ISSUE TITLE
[T2 - P1.a] duda con INC A

### ISSUE THREAD

**Issue by piacabrera** [IIC2343/Syllabus-2023-1#82]
Hola! me surge una duda con respecto a INC A, esto significa incrementar el valor del registro A en 1 unidad?

**Comment by frvalenzuela** [comment]
Hola @piacabrera !

Primero cuidado con el tipo de pregunta, estabas dando una posible respuesta que puede ser considerado una falta a la integridad acádemica. Lo importante es que la pregunta pide modificación de hardware, y si. Incrementa en una unidad.

Saludos!

**Comment by piacabrera** [comment]
Perdón! no pense que afectaba en la respuesta, muchas gracias de todas formas

**Comment by Geeermy** [comment]
Solo como aclaración: es necesario modificar el _hardware_ para habilitar todas las instrucciones pedidas, no obstante, no todas las instrucciones pedidas _podrían requerir_ de modificaciones de _hardware_ (importante, de todas formas, indicar cómo se implementan según sus señales de control, literales, etc.).

De todas formas, recuerda cuidar la forma en que haces las preguntas.

¡Saludos! :)

**Comment by josetomasacuna** [comment]
Hola. Cuál es la diferencia entre INC A e INC (A)?

**Comment by Geeermy** [comment]
¡Hola!

- `INC A` incrementa en una unidad el valor almacenado en el registro A.
- `INC (A)` incrementa en una unidad el valor almacenado en la dirección de memoria a la que apunta `A` (es decir, usas el registro `A` como direccionamiento indirecto para que el dato almacenado en esa dirección de memoria aumente en una unidad).

En los apuntes de programabilidad puedes ver que existe esta instrucción para `B` (`INC (B)`, página 18), por lo que se pide que hagas el símil pero con el registro `A`. :)

¡Saludos!
