### ISSUE TITLE
[T2 - P1.b] Se debe hacer sobre el diagrama de la pregunta 1.a ?

### ISSUE THREAD

**Issue by nicogrecod18** [IIC2343/Syllabus-2023-1#83]
Hola,

Tengo la duda de si hay que hacer las modificaciones pedidas sobre las de las ya realizadas en la pregunta anterior.

Gracias.

**Comment by Geeermy** [comment]
¡Hola!

Puede ser como prefieras, sobre la arquitectura resultante de la 1.a. o sobre la arquitectura del computador básico sin saltos/subrutinas. Lo que sí, si optas por esa opción, no es válido hacer las mismas modificaciones que en la 1.a. jeje.

¡Saludos!

**Comment by nicogrecod18** [comment]
Muchas gracias !!

**Comment by Geeermy** [comment]
@Dafnemami Con lo anterior me refiero a que, por ejemplo, no es válido que crees una instrucción **solo** con lo que modificaste en la 1.a. Puede ser alguna modificación de _hardware_ que se **complemente** con lo que hiciste en la 1.a., pero no que ocupe exclusivamente eso.

¡Saludos!
