### ISSUE TITLE
[T2 - P1.b] Número de iteraciones de la instrucción nueva

### ISSUE THREAD

**Issue by a-ck** [IIC2343/Syllabus-2023-1#84]
Hola, es necesario que la instrucción que inventemos se ejecute en una iteración? o podría ejecutarse en más?

**Comment by Geeermy** [comment]
¡Hola!

Idealmente en una iteración, pero no hay problema si se ejecuta en más de un ciclo. **OJO:** Deben modificar la microarquitectura sí o sí, si simplemente defines una nueva instrucción a partir de combinaciones de señales sobre el _hardware_ ya existente (o el realizado en la pregunta 1.a.), entonces **no se dará puntaje**. Tampoco es válido que modifiques el _hardware_ y que tu instrucción no haga uso de dicha modificación. La idea es que hagan una modificación y la aprovechen para ejecutar una instrucción nueva, eso es lo que se pide.

¡Saludos!

**Comment by a-ck** [comment]
Perfecto, gracias!
