### ISSUE TITLE
[T2 - P1.b] ¿Qué significa "que no sea nuevo"?

### ISSUE THREAD

**Issue by francoschiaffino** [IIC2343/Syllabus-2023-1#85]
Hola! Se puede saber específicamente qué es que no sea nuevo? Que no se haya pasado en clases?

**Comment by frvalenzuela** [comment]
Hola @francoschiaffino !

Que no se haya visto en clases, laboratorios o proyecto. Un nuevo componente sería un circuito que permita una nueva funcionalidad no soportada. Respecto sobre especificaciones de dicho componente recomiendo revisar #79

Si algo no quedo claro, favor hacerlo saber.

Saludos!

**Comment by francoschiaffino** [comment]
Gracias!!

**Comment by martin-iturralde** [comment]
Hola! Se podría hacer uso de material de ayudantías para responder esta pregunta? O esto también se considera como "no nuevo".

**Comment by Geeermy** [comment]
@martin-iturralde  Se considera "nuevo", pero debes citarlo.
