### ISSUE TITLE
[T2 - P1.b] No válido

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2343/Syllabus-2023-1#86]
Hola! en el tercer punto dice:

- Usar combinaciones de señales no utilizadas. Por ejemplo, cargar simultáneamente una operación en los registros A y B

Esto quieres decir que no puedo hacer uso de la señal sobrante en el Mux A?

**Comment by frvalenzuela** [comment]
Hola Margarita!

Si tu nueva instrucción solo usará esa señal para poner una señal constante no podrías hacer uso. Ahora si lo usas con un nuevo componente no habría problema. No es que esa señal este prohibida, pero lo importante es crear una nueva funcionalidad, usar **solo** esa señal, **sin el uso de un componente nuevo** no es válido. Recomiendo revisar #85 y #79 

Saludos!

**Comment by Margarita-Paz** [comment]
Gracias!!

**Comment by Geeermy** [comment]
Hola @Margarita-Paz, para ahondar un poquito: el enunciado dice que se debe agregar _al menos un nuevo componente o conexión_ al diagrama. Es válido usar ese "sobrante" del Mux A para crear una nueva conexión con otros elementos ya existentes en la arquitectura (mas no una señal constante como señaló Felipe).

¡Saludos!
