### ISSUE TITLE
[T2 - P1.a] Lectura y escritura de memoria en un ciclo

### ISSUE THREAD

**Issue by CatalinaFloresP** [IIC2343/Syllabus-2023-1#87]
Hola! En la pregunta 1a no me queda claro cómo, después de haber hecho las modificaciones pedidas, puedo hacer que Data Memory pueda leer y escribir el valor en una misma iteración?

**Comment by Geeermy** [comment]
¡Hola!

La lectura se hace al principio del ciclo al recibir las señales de control de la CU obtenidas a partir del _opcode_ de la instrucción (ya que estas definen la dirección a utilizar según $S_{add}$ y el Mux Address). Posteriormente, en el resto del ciclo esperamos que el circuito se "estabilice", esto es, que se realice la operación esperada en la ALU con los operandos seleccionados y que su resultado se transmita a la unidad de memoria para ser escrito. La gracia es que esta escritura **no se llevará a cabo hasta el siguiente flanco de subida**, que es cuando realmente termina la iteración y comienza la siguiente. Recuerda que esto ocurre porque la memoria de datos, al igual que los registros, están conectadas a una señal _clock_ de forma que actualizan su valor solo en este instante (al tener construcción interna con flip-flops). Así es como la operación se realiza en un solo ciclo. :)

¡Espero que se entienda! Si no te queda 100% claro, en los apuntes de "Programabilidad" hay un esquema súper bueno que muestra cómo se almacenan los datos en los registros (páginas 8-9), funciona de la misma forma para la memoria de datos.

¡Saludos!
