### ISSUE TITLE
[T2 - P1.a] Comparación entre Assembly solicitado y Assembly del proyecto

### ISSUE THREAD

**Issue by fedezang** [IIC2343/Syllabus-2023-1#88]
Hola! tengo la duda si las operaciones de assembly son iguales a como se definen en el proyecto, es decir,
Op1 B,(A) = A op1 (A) guardado en B?

**Comment by Geeermy** [comment]
¡Hola!

No, son distintas. En este caso, lo que se pide es que se guarde `B op1 (A)` en `B` (por eso el enunciado indique que se habilite el direccionamiento indirecto por el registro A).

¡Saludos!

**Comment by Francisco-Morales-R** [comment]
Hola,
Aquí me surgió una duda, ¿Debe ser obligatoriamente B op1 (A)? ¿O puede ser (A) op B?

**Comment by Francisco-Morales-R** [comment]
Perfecto, Muchas gracias!
