### ISSUE TITLE
[T2 P2.a] Duda respecto a los ciclos de RET y POP

### ISSUE THREAD

**Issue by francoschiaffino** [IIC2343/Syllabus-2023-1#90]
Hola! Hay algo que no entiendo de esta pregunta: La idea es modificar el diagrama para que exista una función que ejecute RET y POP ambas juntas en un mismo ciclo, o que tanto RET como POP por separado puedan ejecutar todo lo que tienen que hacer en un solo ciclo?

**Comment by Geeermy** [comment]
¡Hola Franco!

Lo segundo. Que `RET` tome un ciclo en vez de dos y que `POP` tome un ciclo en vez de dos. :)

¡Saludos!

**Comment by francoschiaffino** [comment]
Perfecto, muchas gracias!
