### ISSUE TITLE
[T2 P2.b] Direccionamiento en la máquina de stack

### ISSUE THREAD

**Issue by tomasgbailon** [IIC2343/Syllabus-2023-1#91]
No entiendo si la máquina de stack debe o no dar soporte a manejo de variables (ejemplo ADD A,(DIR)) en memoria y permitir direccionamiento directo e indirecto. Y de ser así, ¿existe alguna restricción sobre quién debe guardar esas variables (el stack o una RAM aparte)?

**Comment by Geeermy** [comment]
¡Hola!

No, no es necesario. La idea es que la arquitectura funcione solo como _stack_ con las funcionalidades descritas en el enunciado. :)

¡Saludos!

**Comment by jrvalenzuela** [comment]
Entonces, para clarificar. En el enunciado dice que siempre se van a tomar el primer o los dos primeros valores en el tope del stack en las operaciones aritméticas y lógicas, y que se podrán guardar variables en el tope del stack. Esto significa que en esta arquitectura ya no se puede obtener un dato de una dirección de memoria directamente? Como lo haríamos con la instrucción ADD A, (Dir) (con Dir una dirección distinta a las que se encuentran al tope del stack)

**Comment by Geeermy** [comment]
Exacto, esa capacidad (y por ende, ese tipo de instrucción) se pierde, solo ocupas la memoria como un _stack_.

¡Saludos!
