### ISSUE TITLE
[T2 P2.b] Instrucciones específicas para saltos y subrutinas

### ISSUE THREAD

**Issue by francoschiaffino** [IIC2343/Syllabus-2023-1#92]
Hola! No me queda claro cuáles específicamente serían las instrucciones que debe soportar la máquina de stack, ya que en la c) y en la d) se menciona que se incluyan saltos y subrutinas respectivamente, pero no entendí cuáles serían para la esta

**Comment by Geeermy** [comment]
¡Hola!

Para el caso de saltos, como se pide implementar los condicionales e incondicionales, puedes asumir que son los mismos que en el computador básico (JMP, JEQ, JNE, etc.). Recuerda que tienes una unidad de control, le puedes pasar a ella la responsabilidad de la revisión de las condiciones.

Para las subrutinas, serían solo las instrucciones CALL y RET (para saltar a una subrutina y volver a la instrucción siguiente al llamado).

El desafío entonces es cómo modificar tu máquina de _stack_ en la pregunta 2.b. para poder ejecutar dichas instrucciones.

¡Saludos (y perdón la hora de respuesta)!

**Comment by francoschiaffino** [comment]
Gracias!!
