### ISSUE TITLE
[T2 P1.a] Señales de control adicionales (issue duplicada)

### ISSUE THREAD

**Issue by AlonsoZamorano** [IIC2343/Syllabus-2023-1#93]
Una consulta, si consideramos modificar el diagrama entonces también puedo crear señales de control nuevas?

**Comment by Geeermy** [comment]
¡Hola! 

Sí, por fis revisar las _issues_ pasadas, esto ya se preguntó en #89.

¡Saludos! (Y buenas noches jeje).

**Comment by AlonsoZamorano** [comment]
Disculpa, leí algunas pero no todas :/
Pero muchas gracias!

**Comment by Geeermy** [comment]
Trata también de ponerle título a las _issues_, no sé por qué nadie lo ha hecho en las últimas 😅 me aseguraré de ponerles título a todas mientras para que sea más fácil revisar. 🙏
