### ISSUE TITLE
[T2 - P2.b] Cargar literales

### ISSUE THREAD

**Issue by jrvalenzuela** [IIC2343/Syllabus-2023-1#94]
Para la parte del enunciado donde dice "cargar valores literales en el tope del stack y también descartarlos", se supone que hay que crear nuevas instrucciones específicamente para esto?

**Comment by Geeermy** [comment]
¡Hola!

Sí. :) Recuerda que en el fondo estás definiendo tú las instrucciones dentro de esta máquina (por eso no las listamos), pero debería haber una que pueda agregar un literal al tope del _stack_ y otra para descartarlo. 😄 Como tip... piensa en las instrucciones `PUSH reg` y `POP reg` del computador básico. :)

¡Saludos!
