### ISSUE TITLE
[T2-P1.a] Duda respecto a los ciclos en una instrucción

### ISSUE THREAD

**Issue by berrazuriz3** [IIC2343/Syllabus-2023-1#95]
Hola, no me queda muy claro en esta pregunta el número de instrucciones que tiene que hacer el circuito en un ciclo, ¿Debe hacer más de una instrucción dentro de un ciclo? Me enredo porque no estoy entendiendo a que se refieren con una solo iteración.

**Comment by Geeermy** [comment]
¡Hola!

1. Recuerda añadir un título explicativo para tu _issue_, por favor.
2. Cada instrucción debe tomar un solo ciclo de _clock_. Una iteración = un ciclo de _clock_. En el caso del computador básico, las únicas instrucciones que toman más de un ciclo (o más de una iteración) son `POP` y `RET`, el resto de las instrucciones toman una sola iteración, para que lo tengas como referencia.

¡Saludos!

**Comment by Dafnemami** [comment]
@Geeermy Estoy un poco confundida que pidan hacer MOV B,(A) (por dar un ejemplo) en un clock, porque tengo que ir buscar el elemento en Mem[A], en lo que ya se me va un clock, y luego en cargar el resultado a RegB ya se me va otro clock.

**Comment by Geeermy** [comment]
@Dafnemami ¡Hola Dafne!

En la última clase vimos un ejemplo de cómo leer y escribir en la memoria de datos en un solo ciclo. Descarga la última versión de la clase 4 (Programabilidad) y revisa las _slides_ 49-53. Esto se relaciona directamente con lo que comentas.

Ahora, respondiendo puntualmente a lo que preguntas: no necesitas un _clock_ para leer y otro para escribir. Puedes hacer la lectura durante el ciclo y llevar a cabo la escritura en el término del ciclo (que corresponde al **flanco de subida de la siguiente iteración**). Te hago el resumen para la instrucción `MOV A,(B)`:

Ciclo 1 - Flanco de subida:
- Incrementa en una unidad el registro `PC`, apuntando a la instrucción `MOV A,(B)`

Ciclo 1 - Resto de la ejecución
- Se transmite el literal al circuito (esto no es relevante en esta instrucción) y el _opcode_ se traduce en las señales de control a ser utilizadas por el resto de componentes:
- Realizada la transmisión de señales, escogerás la dirección $B$ en el `Mux Address` y el dato leído se transmitirá al componente `Mux B`.
- Del `Mux A` escogerás la constante 0 y del `Mux B` escogerás el dato de salida de la memoria (indicado en el paso anterior). Luego, pasarán por la ALU con la operación `ADD` (lo que implica que tendrás `0 + (B) = (B)` y esto lo transmitirás al registro $A$. No obstante, su valor no será escrito en este momento.

Ciclo 2 - Flanco de subida
- Al comenzar el siguiente ciclo, por el flanco de subida se actualizará el registro A (al tener señal $L_a = 1$) y al mismo tiempo el `PC` incrementará en una unidad, apuntando a la siguiente instrucción. Aunque las señales de control cambien por ser otra instrucción, pasado el flanco de subida se bloquea nuevamente el almacenamiento, resguardando así el estado actualizado del registro.

A pesar de que necesitamos que comience el segundo ciclo para finalizar la ejecución de la instrucción, decimos que solo se requiere uno ya que solo necesitamos de él el flanco de subida para el funcionamiento de la carga sobre los registros (que, por detrás, sabemos que son flip-flops que almacenan datos solo en este instante).

Te sugiero que después de leer este resumen, revises bien las diapositivas que te señalé (donde se ve el caso para `INC (B)`) y me comentes por acá si tienes más dudas.

¡Saludos!

**Comment by Dafnemami** [comment]
@Geeermy entendí perfecto, muy agradecida!! abrazos
