### ISSUE TITLE
[T2 P2.c] Uso de más de un registro temporal

### ISSUE THREAD

**Issue by francoschiaffino** [IIC2343/Syllabus-2023-1#96]
Hola! Se pueden utilizar 2 registros temporales de memoria auxiliar? Esto sería solo para guardar info entre ciclos desde una misma instrucción, no entre instrucciones

**Comment by frvalenzuela** [comment]
Hola @francoschiaffino !

Dadas las caracteristicas planteadas en la máquina de stack, no es posible usar dos registros temporales.

Saludos!

**Comment by Geeermy** [comment]
Por favor, poner en el título un resumen de tu pregunta.

¡Saludos!
