### ISSUE TITLE
[T2 P3] Como se entrega la respuesta ?

### ISSUE THREAD

**Issue by nicogrecod18** [IIC2343/Syllabus-2023-1#97]
Hola, 
Les quería preguntar como se entrega esta pregunta, ¿copiamos y pegamos el código en el pdf ? ¿o entregamos un zip con el archivo .txt? ¿Es necesario que el código tenga anotaciones?

Gracias.

**Comment by Geeermy** [comment]
¡Hola!

Acabo de actualizar el buzón para que suban esa pregunta en `.txt` (para facilitar la corrección). No es necesario ni un `.zip` ni un `.pdf`.

Por otra parte, si bien no es estrictamente necesario que tenga anotaciones, se recomienda para que las personas que corrijan tu tarea puedan entender rápidamente lo que estás haciendo (aunque de todas formas se probará en simuladores para verificar).

¡Saludos!

**Comment by nicogrecod18** [comment]
Tengo dos archivos txt, uno comentado y otro sin comentar. Resulta que fui comentando con #, pero el emulador (en windows) se cae, asi que tengo otro archivo con todas las anotaciones borradas, ¿hay alguna forma como "oficial" de comentar el codigo ? ¿o subo los dos archivos ?

**Comment by Geeermy** [comment]
La forma "oficial" para comentarlo debiese ser con `;`

Por ejemplo:

```
MOV A,3 ; Comentario: Esto almacena el literal 3 en el registro A.
```

¿Puedes probar si el simulador deja de caerse así?

**Comment by nicogrecod18** [comment]
También se cae

**Comment by Francisco-Morales-R** [comment]
Hola, yo probé con el emulador de windows, y la forma en la que comento código y no se cae es con:
MOV ...   // Comentario

No sé si con otros emuladores se caerá. En ese caso, ¿También se podría subir algún tipo de pdf que especifique en que emulador se probó? Que yo creé uno, donde también especifico partes del código para que sea más fácil de entender y no tener solo anotaciones.

**Comment by nicogrecod18** [comment]
> Hola, yo probé con el emulador de windows, y la forma en la que comento código y no se cae es con: MOV ... // Comentario
> 
> No sé si con otros emuladores se caerá. En ese caso, ¿También se podría subir algún tipo de pdf que especifique en que emulador se probó? Que yo creé uno, donde también especifico partes del código para que sea más fácil de entender y no tener solo anotaciones.

Muchas gracias, esto me funcionó con el emulador.

**Comment by Geeermy** [comment]
@Francisco-Morales-R ¡Muchas gracias por el comentario! Añadí la extensión `.pdf` a la entrega por si quisieran dar más información. ¿Me podrías confirmar si te deja adjuntar más de un archivo? Sino para hacer algún otro ajuste.

@rosariodominguezm La forma de evaluar va a ser cambiando los _inputs_ de su programa (que puede variar según cómo lo hayan programado). No hay _tests_ de momento, pero lo más importante a mi parecer es que prueben su programa con arreglos de largo par (por ejemplo, $len(arr) = 6$ e impar ($len(arr) = 7$). También probar con largos considerables para verificar que sus algoritmos iteren bien siempre. :)

¡Saludos!

**Comment by Francisco-Morales-R** [comment]
@Geeermy Si deja adjuntar más de un archivo, muchas gracias por las gestiones!
