### ISSUE TITLE
[T2 - P2.b] Duda "registro de memoria auxiliar"

### ISSUE THREAD

**Issue by a-ck** [IIC2343/Syllabus-2023-1#98]
Hola, en el enunciado se menciona un "registro de memoria auxiliar" y no me queda claro si este es aparte de la memoria stack o si es el mismo. Desde ya gracias.

**Comment by Geeermy** [comment]
¡Hola!

Es un registro aparte (como los registros A y B del computador básico). Si ves los diagramas de ejemplo que dejé como archivo compartido en el enunciado, verás que está incluido con ese formato. :)

¡Saludos!

**Comment by a-ck** [comment]
Ya genial, muchas gracias!

**Comment by a-ck** [comment]
Aprovecho de preguntar por acá, solo podemos usar los componentes del archivo de draw.io de la sección "elementos máquina stack" o podemos agregar otras cosas? muxers por ejemplo?

**Comment by Geeermy** [comment]
Sí, de hecho se espera que los agreguen. Lo que incluye el diagrama es lo **mínimo** que necesitan. :)

¡Saludos y buenas noches!

**Comment by berrazuriz3** [comment]
Hola, una duda, cuales son las instrucciones que tenemos que incluir? No me queda claro porque en el enunciado solo dicen set de instrucciones

**Comment by Geeermy** [comment]
@berrazuriz3 Por favor, abre una nueva _issue_ porque esa pregunta es totalmente distinta a la actual y más de una persona la puede tener. 🙏  Tendré la respuesta escrita de antemano. :)
